* Introduction
** Course
   Title- COSC-338, Computer Graphics
   Schedule- M 6-8, W 6-8
   Office Hours -
     I prefer to do them virtually if possible,
       as I live 50 minutes north from here.
     but I also can stay until 9PM on class nights, if needed.
     or I can do them in person, please let me know.
   Group communication
     Slack?  Discord?  Email?  Whatever y'all prefer, but last time my class chose Slack.
   I read a lot from the text, so that you have a copy of what I say.
   You can look at the screen while I read if it's helpful to you, or not if you prefer.
** About Me
*** Name
    Bill Six

*** Graphics experience
    designed, created, and managed a team of 3 to implement
    a 3D graphics subsystem for legacy simulation engine.
    The existing graphics subsystem had been great 1980s-era graphics,
    but we brought them to functional but mediocre 2005-era graphics.

*** Education
    Masters in Computer Science - 2005
    BS in Computer Science - 2005
    BS in Applied Mathematics and Statistics - 2005

*** Work Experience
    Consultant (2005-2009)
    Civil Servant (2009-Present)

*** Teaching Experience
    COSC-338 in Spring 2020.
    Interesting semester to start teaching.
    I don't make powerpoints presentations.
      Feedback as to teaching style welcome.
*** Personal
**** Family
     My wife and I have 3 children, twins age 6, oldest age 9
**** Hobbies
***** playing music
      on guitar, piano, bass and drums
***** video games
        Nintendo Games
          Mario, Zelda, everything Nintendo
        Street Fighter 5
        FPSs
***** programming computers
        Lisp, Python, C, Assembly, Haskell, Smalltalk-80 are my favorites
***** math
        Calc 1 is my favorite subject of all time.
        Current interests are in multivariate math, including Geometric Algebra,
          the best math that the 1870s have to offer

** Subject Matter
*** What this course is

    Boring description:

    Fundamentals for programming 2D/3D computer graphics

    The field is a really fun intersection of computer programming and math.
      Most of the math is:
        * function composition.  (f o g)(x) = f(g(x))
        * inverses.  f^-1(f(x)) = x
        * high school trigonometry, proportional triangles
      And the math is applicable in other fields besides computer graphics
    A background in Linear Algebra is useful, but not required, as we re-derive
    it from scratch in this class.

*** Reading Materials
    billsix.github.io/modelviewprojection
      This is an online book that I wrote, and am continuing to improve,
      in order to explain the math behind computer graphics
      in a way that someone with a high school education in math can
      understand
    and OpenGL SuperBible v4
      an excellent book with tons of demo code, but which is lacking
      in quality explanations of the math

    In my experience, books in high school were friendly to the novice,
    but starting in college, that was no longer the case; for me at least.
    In retrospect, there are many great books that are
    phenomenal to those who already understand the material,
    but are inpenetrable to the novice.  My emphasis in this course
    is on the novice, and I'd like feedback at the end of the course,
    positive or negative.  Pull requests to github are even better.

*** What you will be able to write/understand
    [Run the ch01 demo, talk about levels of realism]
    [Run mvpVisualization/5/demo5.py]
    [Run the McNopper Demos]

*** Syllabus
    [display it]
    [discuss how the grading is set up]

** Introductions from students to me

    I wish to know something about my students, and I intend to
    know you all by name within the first 3 weeks.

    Some ideas of what to talk about, and there are no wrong answers.

    Name
    Major
    Favorite class
    Least favorite class
    Experience in programming and in math
    Hobbies
    Why did you sign up for this class, and do you have any specific things you're looking to learn?


** Begin lessons
   start with model view projection
