FROM registry.fedoraproject.org/fedora:42

ARG BUILD_DOCS=@BUILD_DOCS_FLAG@
ARG BUILD_PDF=@BUILD_PDF_FLAG@
ARG BUILD_HTML=@BUILD_HTML_FLAG@
ARG USE_X_WINDOWS=@USE_X_WINDOWS@
ARG USE_EMACS=@USE_EMACS@
ARG USE_IMGUI=@USE_IMGUI@

COPY entrypoint/dotfiles/ /root/

RUN dnf install -y \
                   glfw \
                   python3-glfw \
		   python3-numpy \
                   # python3-openimageio \
		   python3-pillow \
                   python3-pip \
                   python3-pyopengl \
                   python3-pytest \
		   # python3-pytest-lsp \
                   python3-wxpython4  \
                   ruff \
                   tmux ; \
    if [ "$BUILD_DOCS" = "1" ]; then \
       dnf install -y \
                   autoconf \
                   automake \
                   aspell \
                   aspell-en \
        	   gnuplot \
                   graphviz \
                   ImageMagick \
                   inkscape \
                   latexmk \
                   make \
                   mathjax \
                   mathjax-main-fonts \
                   mathjax-math-fonts \
                   python3-furo \
                   python3-matplotlib \
                   python3-sphinx_rtd_theme \
                   python3-sphinxcontrib-bibtex \
                   texlive \
                   texlive-anyfontsize \
                   texlive-dvipng \
                   texlive-dvisvgm \
                   texlive-standalone; \
       # cache matplotlib stuff \
       python3 -c "import matplotlib.pyplot as plt; plt.plot([1,2,3], [4,5,6]); plt.show()" ; \
    fi ;
    if [ "$USE_X_WINDOWS" = "1" ]; then \
       dnf install -y \
                   libglvnd-gles \
                   libXcomposite \
                   libXcursor \
                   libXdamage \
                   libXfixes \
                   libXft \
                   libXi \
                   libXinerama \
                   libXmu \
                   libXrandr \
                   libXrender \
                   libXres \
                   libXtst \
                   libXv \
                   libXxf86vm \
                   mesa-dri-drivers  \
                   mesa-libGLU-devel; \
    fi ; \
    if [ "$USE_EMACS" = "1" ]; then \
       dnf install -y \
                   emacs \
                   npm; \
       # install pyright for lsp \
       npm install -g pyright ;\
       emacs --batch --load /root/.emacs.d/install-melpa-packages.el ; \
       echo "alias ls='ls --color=auto'" >> ~/.bashrc \
     fi ; \
    if [ "$USE_JUPYTER" = "1" ]; then \
       dnf install -y \
        	   ffmpeg \
        	   firefox \
        	   jupyter \
        	   jupyterlab  \
        	   jupytext \
                   make \
                   mathjax \
                   mathjax-main-fonts \
                   mathjax-math-fonts \
        	   python3-jupyterlab-jupytext \
        	   python3-jupyter-lsp \
        	   python3-lsp-server; \
                 python3-sympy \
       # install pyright for lsp \
       npm install -g pyright  \
     fi ;
     # clean out dnf \
     dnf clean all && \
     # install moviepy until fedora takes it \
     python3 -m pip install --break-system-packages --root-user-action=ignore moviepy;
     if [ "$USE_IMGUI" = "1" ]; then \
       dnf install -y \
                   autoconf \
                   automake \
                   g++ \
        	   gcc \
                   python3-devel; \
        # install imgui, until I replace imgui code with wxpython4 \
        cd ~/ && \
        git clone https://github.com/billsix/pyimgui.git && \
        cd pyimgui && \
        git submodule init && git submodule update && \
        python3 -m pip install --break-system-packages --root-user-action=ignore .
     fi ;






ENTRYPOINT ["/entrypoint.sh"]
