FROM registry.fedoraproject.org/fedora:42

ARG BUILD_DOCS=@BUILD_DOCS_FLAG@
ARG BUILD_PDF=@BUILD_PDF_FLAG@
ARG BUILD_HTML=@BUILD_HTML_FLAG@
ARG USE_X_WINDOWS=@USE_X_WINDOWS@
ARG USE_EMACS=@USE_EMACS@
ARG USE_IMGUI=@USE_IMGUI@
ARG USE_JUPYTER=@USE_JUPYTER@
ARG USE_SPYDER=@USE_SPYDER@

COPY entrypoint/dotfiles/ /root/

RUN dnf install -y \
                   glfw \
                   python3-glfw \
		   python3-numpy \
                   python3-openimageio \
		   python3-pillow \
                   python3-pip \
                   python3-pyopengl \
                   python3-pytest \
		   python3-pytest-lsp \
                   python3-sympy \
                   python3-wxpython4  \
                   ruff \
                   tmux ; \
    if [ "$BUILD_DOCS" = "1" ]; then \
       dnf install -y \
                   autoconf \
                   automake \
                   aspell \
                   aspell-en \
        	   gnuplot \
                   graphviz \
                   ImageMagick \
                   inkscape \
                   latexmk \
                   make \
                   mathjax \
                   mathjax-main-fonts \
                   mathjax-math-fonts \
                   python3-furo \
                   python3-matplotlib \
                   python3-sphinx_rtd_theme \
                   python3-sphinxcontrib-bibtex \
                   texlive \
                   texlive-anyfontsize \
                   texlive-dvipng \
                   texlive-dvisvgm \
                   texlive-standalone; \
       python3 -c "import matplotlib.pyplot as plt; plt.plot([1,2,3], [4,5,6]); plt.show()" ; \
    fi ; \
    if [ "$USE_X_WINDOWS" = "1" ]; then \
       dnf install -y \
                   libglvnd-gles \
                   libXcomposite \
                   libXcursor \
                   libXdamage \
                   libXfixes \
                   libXft \
                   libXi \
                   libXinerama \
                   libXmu \
                   libXrandr \
                   libXrender \
                   libXres \
                   libXtst \
                   libXv \
                   libXxf86vm \
                   mesa-dri-drivers  \
                   mesa-libGLU-devel; \
    fi ;  \
    dnf clean all

RUN if [ "$USE_EMACS" = "1" ]; then \
       dnf install -y \
                   emacs \
        	   python3-lsp-server \
                   npm && \
       npm install -g pyright && \
       emacs --batch --load /root/.emacs.d/install-melpa-packages.el && \
       echo "alias ls='ls --color=auto'" >> ~/.bashrc ;\
     fi ;  \
    dnf clean all

RUN if [ "$USE_JUPYTER" = "1" ]; then \
       dnf install -y \
        	   ffmpeg \
        	   firefox \
        	   jupyter \
        	   jupyterlab  \
        	   jupytext \
                   make \
                   mathjax \
                   mathjax-main-fonts \
                   mathjax-math-fonts \
        	   python3-jupyterlab-jupytext \
        	   python3-jupyter-lsp  && \
       python3 -m pip install --break-system-packages --root-user-action=ignore moviepy; \
    fi;  \
    dnf clean all

RUN if [ "$USE_IMGUI" = "1" ]; then \
       dnf install -y \
                   autoconf \
                   automake \
                   g++ \
        	   gcc \
                   python3-devel && \
        cd ~/ && \
        git clone https://github.com/billsix/pyimgui.git && \
        cd pyimgui && \
        git submodule init && git submodule update && \
        python3 -m pip install --break-system-packages --root-user-action=ignore . ;\
     fi ;  \
    dnf clean all

RUN if [ "$USE_SPYDER" = "1" ]; then \
      dnf install -y spyder && \
      mkdir -p ~/.config/spyder-py3/config && \
      echo "[editor]" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "font/family = Source Code Pro" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "font/size = 24" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "[file_explorer]" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "visible = False" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "[tours]" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "show_tour_message = False" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "[appearance]" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "font/family = Adwaita Mono" >> ~/.config/spyder-py3/config/spyder.ini && \
      echo "font/size = 18" >> ~/.config/spyder-py3/config/spyder.ini; \
    fi ;  \
    dnf clean all



ENTRYPOINT ["/entrypoint.sh"]
