# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""``pgzero_gl`` -- a PyGame Zero compatibility shim on GLFW + OpenGL 3.3 core.

Part of the ModelViewProjection port of "Code the Classics" from PyGame Zero to
modern OpenGL. The original games are (c) Raspberry Pi Press and their authors
(Andrew Gillett et al.; graphics by Dan Malone; audio by Allister Brimble). This
shim is the rendering/input/audio layer that lets the original game logic run
unmodified on OpenGL.

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

A ported game replaces its first line ::

    import pgzero, pgzrun, pygame

with ::

    from pgzero_gl import *

and otherwise keeps PyGame Zero's globals: :class:`Actor`, :data:`screen`,
:data:`keyboard`, :data:`keys`, :data:`sounds`, :data:`music`, :data:`images`,
:class:`Rect`, :data:`mixer` (a no-op stand-in for pygame.mixer) and
:func:`go` (PyGame Zero's ``pgzrun.go``). Deeper pygame APIs are real
submodules imported explicitly: :mod:`pgzero_gl.geometry` (Rect/ZRect;
vectors come from gacalc directly),
:mod:`pgzero_gl.draw`, :mod:`pgzero_gl.transform`, :mod:`pgzero_gl.surface`,
:mod:`pgzero_gl.joystick`, :mod:`pgzero_gl.mask`.  (Until 2026-07-08 the shim
instead forged synthetic ``pygame``/``pgzero``/``pgzrun`` modules into
``sys.modules`` so upstream import lines could stay verbatim; that was retired
with the byte-faithfulness rule -- imports now say what they mean.)
"""

from __future__ import annotations

import functools
import os
from typing import Any

from . import audio, context
from .actor import Actor
from .audio import music
from .geometry import Rect, ZRect
from .input import keyboard, keys
from .resources import images, sounds
from .runner import go, quit_game
from .screen import screen

__all__ = [
    "Actor",
    "Rect",
    "ZRect",
    "keyboard",
    "keys",
    "images",
    "sounds",
    "music",
    "screen",
    "go",
    "exit",
    "mixer",
]


def exit() -> None:
    """pgzero exposes a builtin exit() that quits the game."""
    quit_game()


# --- the mixer stand-in -----------------------------------------------------
# A no-op object matching the slice of pygame.mixer's API the games' audio
# boilerplate calls (real audio is handled by pgzero_gl.audio).  Exported as
# `mixer` so the games' init/quit/set_num_channels lines keep working with
# `pygame.mixer.` replaced by `mixer.`.


class _Mixer:
    """A no-op stand-in for ``pygame.mixer`` (audio is handled by :mod:`audio`)."""

    def quit(self) -> None:
        pass

    def init(self, *a: Any, **k: Any) -> None:
        pass

    def set_num_channels(self, *a: Any, **k: Any) -> None:
        pass

    def find_channel(self, *a: Any, **k: Any) -> None:
        return None

    def get_busy(self) -> bool:
        return False

    Sound = staticmethod(lambda path: _MixerSound(path))


@functools.lru_cache(maxsize=64)
def _pooled_sound(path: str) -> audio.Sound:
    """One decoded, voice-pooled Sound per file (see audio.Sound's pooling)."""
    return audio.Sound(path)


class _MixerSound:
    """``pygame.mixer.Sound`` work-alike over the pooled audio backend.

    avenger constructs one of these per distance-attenuated shot
    (``mixer.Sound("sounds/x.ogg")`` then ``set_volume``); the old no-op stub
    silently dropped every such sound (found 2026-07-09). A naive
    one-audio.Sound-per-call would leak miniaudio streams (dropped Playbacks
    have no finalizer -- see audio.py), so the decoded sound is pooled by
    path and this wrapper's volume is applied PER PLAY to the voice acquired
    for that play: pygame's per-instance-volume semantics, without the leak.
    """

    def __init__(self, path: Any) -> None:
        # pygame resolves relative to the game folder; so do we.
        self._sound = _pooled_sound(
            os.path.join(context.get_asset_root(), str(path))
        )
        self._volume: float = 1.0

    def set_volume(self, v: float) -> None:
        self._volume = float(v)

    def get_volume(self) -> float:
        return self._volume

    def play(self, *a: Any, **k: Any) -> None:
        self._sound.play(volume=self._volume)

    def stop(self) -> None:
        self._sound.stop()


mixer: Any = _Mixer()
