# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""Shared type aliases and structural (``Protocol``) types for the shim.

These exist so the per-module annotations stay short and consistent. Nothing
here imports another shim module, so it is import-cycle-safe to pull from
anywhere in ``pgzero_gl``.
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Protocol, Tuple, Union

import numpy as np
from numpy.typing import NDArray

# A colour as the games supply it: 3 (RGB) or 4 (RGBA) channels, each 0-255.
ColorRGB = Tuple[int, int, int]
ColorRGBA = Tuple[int, int, int, int]
Color = Union[ColorRGB, ColorRGBA]

# A 2-D position in PyGame Zero's top-left-origin, y-down pixel space. ``Point``
# is the concrete pair the shim returns; ``PointLike`` is what it accepts (the
# games pass tuples, lists, or vectors -- anything index/unpack-able as x, y).
Point = Tuple[float, float]
PointLike = Sequence[float]


class Drawable(Protocol):
    """Anything :meth:`Screen.blit` can draw: an image-like backed by a GL texture.

    Both :class:`pgzero_gl.resources.Image` and
    :class:`pgzero_gl.surface.Surface` satisfy this.
    """

    width: int
    height: int

    def gl_texture(self) -> int: ...


class RGBASource(Protocol):
    """Anything backed by an ``H x W x 4`` ``uint8`` RGBA CPU buffer.

    Used where the shim reads pixels (collision masks, compositing): both
    :class:`pgzero_gl.resources.Image` and :class:`pgzero_gl.surface.Surface`
    expose ``rgba``.
    """

    rgba: NDArray[np.uint8]
