# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- the Actor sprite.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# actor.py -- PyGame Zero's Actor: an image positioned by a (default: centre)
# anchor, in top-left-origin pixel space.  We reproduce its behaviour exactly so
# ported game code is unchanged:
#   * `.image = "name"` (re)loads images/name.png, keeping the anchor position;
#   * `.pos`/`.x`/`.y` are the anchor position; `.left`/`.center`/... are rect
#     edges delegated to an underlying Rect;
#   * `.angle` rotates about the anchor;
#   * arbitrary game attributes (`.dx`, `.speed`, ...) pass through to the
#     instance dict.

from math import atan2, degrees, sqrt

from . import context
from .geometry import Rect

_ANCHOR_FRAC = {
    "x": {"left": 0.0, "center": 0.5, "middle": 0.5, "right": 1.0},
    "y": {"top": 0.0, "center": 0.5, "middle": 0.5, "bottom": 1.0},
}

# rect attributes delegated straight through to the underlying Rect
_DELEGATED = {
    "left", "right", "top", "bottom", "centerx", "centery",
    "center", "topleft", "topright", "bottomleft", "bottomright",
    "midtop", "midbottom", "midleft", "midright",
    "width", "height", "size", "w", "h",
}


def _calc(value, dim, total):
    if isinstance(value, str):
        return total * _ANCHOR_FRAC[dim][value]
    return float(value)


class Actor:
    def __init__(self, image, pos=None, anchor=None, **kwargs):
        object.__setattr__(self, "_rect", Rect(0, 0, 0, 0))
        object.__setattr__(
            self, "_anchor_value", anchor if anchor is not None else ("center", "center")
        )
        object.__setattr__(self, "_angle", 0.0)
        object.__setattr__(self, "_image", None)
        object.__setattr__(self, "_image_name", None)

        self._set_image(image)

        if pos is not None:
            self._set_pos(pos)
        else:
            sym = {k: v for k, v in kwargs.items() if k in _DELEGATED}
            if sym:
                k, v = next(iter(sym.items()))
                setattr(self._rect, k, v)
            else:
                self._rect.topleft = (0, 0)

    # -- image ----------------------------------------------------------------
    def _set_image(self, image):
        from .resources import images

        img = images.load(image) if isinstance(image, str) else image
        keep = None
        if self._image is not None:
            keep = self._anchor_pos()
        object.__setattr__(self, "_image", img)
        object.__setattr__(
            self, "_image_name", image if isinstance(image, str) else None
        )
        self._rect.size = (img.width, img.height)
        if keep is not None:
            self._set_pos(keep)

    # -- anchor / position ----------------------------------------------------
    def _anchor_offset(self):
        av = self._anchor_value
        return (
            _calc(av[0], "x", self._rect.width),
            _calc(av[1], "y", self._rect.height),
        )

    def _anchor_pos(self):
        ox, oy = self._anchor_offset()
        return (self._rect.left + ox, self._rect.top + oy)

    def _set_pos(self, pos):
        ox, oy = self._anchor_offset()
        self._rect.left = pos[0] - ox
        self._rect.top = pos[1] - oy

    # -- attribute routing ----------------------------------------------------
    def __getattr__(self, name):
        # only called when normal lookup fails
        if name == "x":
            return self._anchor_pos()[0]
        if name == "y":
            return self._anchor_pos()[1]
        if name == "pos":
            return self._anchor_pos()
        if name == "angle":
            return self._angle
        if name == "image":
            return self._image_name
        if name == "anchor":
            return self._anchor_value
        if name in _DELEGATED:
            return getattr(self._rect, name)
        raise AttributeError(name)

    def __setattr__(self, name, value):
        if name.startswith("_"):
            object.__setattr__(self, name, value)
            return
        if name == "x":
            self._set_pos((value, self._anchor_pos()[1]))
            return
        if name == "y":
            self._set_pos((self._anchor_pos()[0], value))
            return
        if name == "pos":
            self._set_pos(value)
            return
        if name == "angle":
            object.__setattr__(self, "_angle", value)
            return
        if name == "image":
            self._set_image(value)
            return
        if name == "anchor":
            object.__setattr__(self, "_anchor_value", value)
            return
        if name in _DELEGATED:
            setattr(self._rect, name, value)
            return
        object.__setattr__(self, name, value)

    # -- drawing & geometry ---------------------------------------------------
    def draw(self):
        context.require_renderer().draw_image(
            self._image,
            self._rect.topleft,
            angle=self._angle,
            anchor=self._anchor_pos(),
        )

    def angle_to(self, target):
        tx, ty = target.pos if isinstance(target, Actor) else target
        mx, my = self.pos
        return degrees(atan2(my - ty, tx - mx))  # screen y inverted

    def distance_to(self, target):
        tx, ty = target.pos if isinstance(target, Actor) else target
        mx, my = self.pos
        return sqrt((tx - mx) ** 2 + (ty - my) ** 2)

    def colliderect(self, other):
        o = other._rect if isinstance(other, Actor) else other
        return self._rect.colliderect(o)

    def collidepoint(self, *p):
        return self._rect.collidepoint(*p)

    def __iter__(self):
        return iter(self._rect)
