# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""The :class:`Actor` sprite -- PyGame Zero's positioned, anchored image.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

An :class:`Actor` is an image positioned by an anchor (default: centre) in
top-left-origin pixel space. We reproduce pgzero's behaviour exactly so ported
game code is unchanged:

* ``actor.image = "name"`` (re)loads ``images/name.png``, keeping the anchor
  position;
* ``actor.pos`` / ``.x`` / ``.y`` are the anchor position; ``.left`` / ``.center``
  / ... are rect edges delegated to an underlying :class:`Rect`;
* ``actor.angle`` rotates about the anchor;
* arbitrary game attributes (``.dx``, ``.speed``, ...) are ordinary instance
  attributes.

All of that used to be routed through ``__getattr__``/``__setattr__`` string
ladders (upstream pgzero's open-world design, built so beginners never
declare anything). The 2026-07-09 shim-dynamism audit instrumented all 10
games and found the attribute surface is CLOSED -- x/y alone were 93% of
2.5M dynamic reads, and nothing ever used the open-world read path -- so the
magic names and the rect delegations are now real (static) properties, and
game data attributes hit the instance dict natively. See
tasks/ctc-shim-dynamism-audit.md.
"""

from __future__ import annotations

from collections.abc import Iterator
from math import atan2, degrees, sqrt
from typing import Any, Tuple, Union

from gacalc.g2 import Vector2

from . import context
from ._types import Anchor, Drawable, PointLike
from .geometry import ZRect, _RectBase
from .resources import images

_ANCHOR_FRAC = {
    "x": {"left": 0.0, "center": 0.5, "middle": 0.5, "right": 1.0},
    "y": {"top": 0.0, "center": 0.5, "middle": 0.5, "bottom": 1.0},
}

# rect attributes delegated straight through to the underlying Rect
_DELEGATED = {
    "left",
    "right",
    "top",
    "bottom",
    "centerx",
    "centery",
    "center",
    "topleft",
    "topright",
    "bottomleft",
    "bottomright",
    "midtop",
    "midbottom",
    "midleft",
    "midright",
    "width",
    "height",
    "size",
    "w",
    "h",
}


def _calc(value: Any, dim: str, total: float) -> float:
    """Resolve an anchor component: a named fraction (``"center"``) times ``total``,
    or a literal pixel offset."""
    if isinstance(value, str):
        return total * _ANCHOR_FRAC[dim][value]
    return float(value)


class Actor:
    """A pgzero ``Actor``: an image positioned by a (default-centre) anchor."""

    # Private state backing the properties below.
    # ZRect (float coords): an Actor's anchor position is stored here, so
    # movement at non-integer speeds keeps its sub-pixel precision instead of
    # truncating each frame (pygame.Rect / our int Rect would drift).
    _rect: ZRect
    _anchor_value: Anchor
    _angle: float
    _image: Drawable | None
    _image_name: str | None
    # memoized anchor offset; None = recompute (invalidated when the anchor
    # or the rect size changes)
    _offset_cache: Tuple[float, float] | None

    def __init__(
        self,
        image: Union[str, Drawable],
        pos: PointLike | None = None,
        anchor: Anchor | None = None,
        **kwargs: float,
    ) -> None:
        self._rect = ZRect(0, 0, 0, 0)
        self._offset_cache = None
        self._anchor_value = (
            anchor if anchor is not None else ("center", "center")
        )
        self._angle = 0.0
        self._image = None
        self._image_name = None

        self._set_image(image)

        if pos is not None:
            self._set_pos(pos)
        else:
            sym: dict[str, Any] = {
                k: v for k, v in kwargs.items() if k in _DELEGATED
            }
            if sym:
                k, v = next(iter(sym.items()))
                setattr(self._rect, k, v)
            else:
                self._rect.topleft = (0, 0)

    # -- image ----------------------------------------------------------------
    def _set_image(self, image: Union[str, Drawable]) -> None:
        """Set/replace the sprite image (by name or Image), preserving the anchor pos."""
        img = images.load(image) if isinstance(image, str) else image
        keep: Tuple[float, float] | None = None
        if self._image is not None:
            keep = self._anchor_pos()
        self._image = img
        self._image_name = image if isinstance(image, str) else None
        self._rect.size = (img.width, img.height)
        self._offset_cache = None  # size feeds the anchor offset
        if keep is not None:
            self._set_pos(keep)

    # -- anchor / position ----------------------------------------------------
    def _anchor_offset(self) -> Tuple[float, float]:
        """Return the anchor's pixel offset from the rect's top-left corner.

        Memoized: x/y reads are the games' hottest attribute path (93% of
        2.5M dynamic reads in the 2026-07-09 audit), and the offset only
        changes when the anchor or the sprite size does."""
        cached = self._offset_cache
        if cached is not None:
            return cached
        av = self._anchor_value
        offset = (
            _calc(value=av[0], dim="x", total=self._rect.width),
            _calc(value=av[1], dim="y", total=self._rect.height),
        )
        self._offset_cache = offset
        return offset

    def _anchor_pos(self) -> Tuple[float, float]:
        """Return the current anchor position in pixel space."""
        ox, oy = self._anchor_offset()
        return (self._rect.left + ox, self._rect.top + oy)

    def _set_pos(self, pos: PointLike) -> None:
        """Move the sprite so its anchor lands on ``pos``."""
        ox, oy = self._anchor_offset()
        # unpack rather than index: pos may be a tuple OR a gacalc vector
        # (iterable of coordinates, not indexable)
        px, py = pos
        self._rect.left = px - ox
        self._rect.top = py - oy

    # -- the pgzero attribute surface, as REAL properties ---------------------
    # (static descriptors; formerly a __getattr__/__setattr__ string ladder)
    @property
    def x(self) -> float:
        return self._anchor_pos()[0]

    @x.setter
    def x(self, value: float) -> None:
        self._set_pos((value, self._anchor_pos()[1]))

    @property
    def y(self) -> float:
        return self._anchor_pos()[1]

    @y.setter
    def y(self, value: float) -> None:
        self._set_pos((self._anchor_pos()[0], value))

    @property
    def pos(self) -> Vector2:
        # the anchor position AS a geometric-algebra vector: game code adds
        # velocities (``self.pos + self.velocity``), takes differences
        # (``player.pos - self.pos``), and measures magnitudes directly.
        # (Anything needing a tuple unpacks it -- gacalc vectors iterate.)
        px, py = self._anchor_pos()
        return Vector2(px, py)

    @pos.setter
    def pos(self, value: PointLike) -> None:
        self._set_pos(value)

    @property
    def angle(self) -> float:
        return self._angle

    @angle.setter
    def angle(self, value: float) -> None:
        self._angle = value

    @property
    def image(self) -> str:
        # the games always address images by name; an Actor built from a raw
        # Image object (no name) reads as "" rather than None
        return self._image_name or ""

    @image.setter
    def image(self, value: Union[str, Drawable]) -> None:
        self._set_image(value)

    @property
    def anchor(self) -> Anchor:
        return self._anchor_value

    @anchor.setter
    def anchor(self, value: Anchor) -> None:
        self._anchor_value = value
        self._offset_cache = None

    # rect edges/centres, delegated to the underlying ZRect -- exactly the
    # subset the 10 games touch (per the 2026-07-09 audit; the shim's charter
    # is the subset the games use, so the 12 unused pygame.Rect virtual
    # attributes are deliberately NOT reproduced here).
    @property
    def left(self) -> float:
        return self._rect.left

    @left.setter
    def left(self, value: float) -> None:
        self._rect.left = value

    @property
    def top(self) -> float:
        return self._rect.top

    @top.setter
    def top(self, value: float) -> None:
        self._rect.top = value

    @property
    def bottom(self) -> float:
        return self._rect.bottom

    @bottom.setter
    def bottom(self, value: float) -> None:
        self._rect.bottom = value

    @property
    def centerx(self) -> float:
        return self._rect.centerx

    @centerx.setter
    def centerx(self, value: float) -> None:
        self._rect.centerx = value

    @property
    def centery(self) -> float:
        return self._rect.centery

    @centery.setter
    def centery(self, value: float) -> None:
        self._rect.centery = value

    @property
    def center(self) -> Tuple[float, float]:
        return self._rect.center

    @center.setter
    def center(self, value: PointLike) -> None:
        self._rect.center = value

    @property
    def width(self) -> float:
        return self._rect.width

    @width.setter
    def width(self, value: float) -> None:
        self._rect.width = value
        self._offset_cache = None  # size feeds the anchor offset

    @property
    def height(self) -> float:
        return self._rect.height

    @height.setter
    def height(self, value: float) -> None:
        self._rect.height = value
        self._offset_cache = None  # size feeds the anchor offset

    # -- drawing & geometry ---------------------------------------------------
    def draw(self) -> None:
        """Draw the sprite at its current position/angle via the active renderer."""
        # _set_image ran in __init__, so _image is always bound by draw time
        assert self._image is not None
        context.require_renderer().draw_image(
            image=self._image,
            topleft=self._rect.topleft,
            angle=self._angle,
            anchor=self._anchor_pos(),
        )

    def angle_to(self, target: Union["Actor", PointLike]) -> float:
        """Return the angle (degrees) from this actor to ``target`` (Actor or point)."""
        tx, ty = target.pos if isinstance(target, Actor) else target
        mx, my = self.pos
        return degrees(atan2(my - ty, tx - mx))  # screen y inverted

    def distance_to(self, target: Union["Actor", PointLike]) -> float:
        """Return the distance from this actor to ``target`` (Actor or point)."""
        tx, ty = target.pos if isinstance(target, Actor) else target
        mx, my = self.pos
        return sqrt((tx - mx) ** 2 + (ty - my) ** 2)

    def colliderect(self, other: Union["Actor", "_RectBase[Any]"]) -> bool:
        """Return whether this actor's rect overlaps ``other`` (Actor or Rect)."""
        o = other._rect if isinstance(other, Actor) else other
        return self._rect.colliderect(o)

    def collidepoint(self, *p: Any) -> bool:
        """Return whether the point ``p`` lies within this actor's rect."""
        return self._rect.collidepoint(*p)

    def __iter__(self) -> Iterator[float]:
        return iter(self._rect)
