# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- sound + music, without pygame.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# audio.py -- PyGame Zero gets audio from pygame.mixer (SDL).  We deliberately
# avoid pygame here (the project's host runs an SDL2-on-SDL3 shim that breaks
# SDL audio).  Instead we use `just_playback` (a thin wrapper over the bundled
# miniaudio C library; ogg/wav/mp3, per-instance volume + looping).
#
# Audio is BEST EFFORT: if the backend can't be imported or a device can't be
# opened, every call becomes a no-op.  The original games already wrap sound in
# try/except, so silence never breaks gameplay -- and on-screen GL is what gets
# human-verified here anyway (no audio device in the build container).

import os

from . import context

try:
    from just_playback import Playback as _Playback

    _BACKEND = True
except Exception:  # pragma: no cover - depends on runtime env
    _Playback = None
    _BACKEND = False


def available():
    return _BACKEND


class Sound:
    """A single sound effect, loaded from a file path.  `play()` spins up a
    fresh playback each call so effects can overlap."""

    def __init__(self, path):
        self.path = path
        self._instances = []

    def play(self, loops=0):
        if not _BACKEND:
            return
        try:
            pb = _Playback()
            pb.load_file(self.path)
            if loops != 0:
                pb.loop_at_end(True)
            pb.play()
        except Exception:
            return
        # Keep references so they aren't garbage-collected mid-play; drop any
        # that have finished.
        self._instances = [p for p in self._instances if _active(p)]
        self._instances.append(pb)

    def stop(self):
        for p in self._instances:
            try:
                p.stop()
            except Exception:
                pass
        self._instances.clear()


class _Music:
    """The single streamed background track (pgzero's `music` object)."""

    def __init__(self):
        self._pb = None
        self._volume = 1.0

    def _path(self, name):
        base = os.path.join(context.get_asset_root(), "music", name)
        if os.path.isfile(base):
            return base
        for ext in ("ogg", "mp3", "wav"):
            p = base + "." + ext
            if os.path.exists(p):
                return p
        return None

    def play(self, name):
        if not _BACKEND:
            return
        self.stop()
        p = self._path(name)
        if not p:
            return
        try:
            self._pb = _Playback()
            self._pb.load_file(p)
            self._pb.loop_at_end(True)
            self._pb.set_volume(self._volume)
            self._pb.play()
        except Exception:
            self._pb = None

    def play_once(self, name):
        if not _BACKEND:
            return
        self.stop()
        p = self._path(name)
        if not p:
            return
        try:
            self._pb = _Playback()
            self._pb.load_file(p)
            self._pb.set_volume(self._volume)
            self._pb.play()
        except Exception:
            self._pb = None

    def set_volume(self, v):
        self._volume = v
        if self._pb is not None:
            try:
                self._pb.set_volume(v)
            except Exception:
                pass

    def get_volume(self):
        return self._volume

    def stop(self):
        if self._pb is not None:
            try:
                self._pb.stop()
            except Exception:
                pass
            self._pb = None

    def fadeout(self, seconds):
        # No real fade in the backend; stop is a faithful-enough fallback.
        self.stop()


def _active(pb):
    try:
        return pb.active
    except Exception:
        return False


music = _Music()
