# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- shared runtime state.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# context.py -- a tiny holder for process-wide state that several shim modules
# need but which is only known once the game starts: the active Renderer (set
# after the GL context is created) and the asset root directory.

import os
import sys

# The active renderer.Renderer instance.  None until runner.run() creates the
# GL context.  Drawing before then raises a clear error.
renderer = None

# The active GLFW window handle (set by the runner); used by exit().
window = None

# True once glfw.init() has succeeded.  Joystick queries must not touch GLFW
# before this (game modules call setup_joystick_controls() at import time, before
# the window/loop exist).
glfw_ready = False

# Directory that contains the game's images/, sounds/, music/ folders.
# None means "resolve lazily" -- because game objects (and thus image/sound
# loads) are routinely created at module-import time, BEFORE go() runs, we infer
# the root from the main script's location when it hasn't been set explicitly.
asset_root = None


def get_asset_root():
    if asset_root is not None:
        return asset_root
    main = sys.modules.get("__main__")
    main_file = getattr(main, "__file__", None)
    if main_file:
        return os.path.dirname(os.path.abspath(main_file))
    return os.getcwd()


def require_renderer():
    if renderer is None:
        raise RuntimeError(
            "No GL renderer yet -- drawing happens inside the game loop "
            "(after go()).  Don't draw at import time."
        )
    return renderer
