# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""Rectangles -- ``pygame.Rect`` and pgzero's float ``ZRect``.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

This module used to carry pygame ``Vector2``/``Vector3`` work-alikes; the
games now use the gacalc geometric-algebra vectors directly
(``gacalc.g2.Vector2`` / ``gacalc.g3.Vector3`` -- see the ctc section of the
repo CLAUDE.md), so only the rectangles remain.  Position-like parameters
here and across the shim are typed :data:`VectorLike` / ``Any`` -- pygame
accepts any indexable/iterable pair, including gacalc vectors.
"""

from __future__ import annotations

from collections.abc import Iterator
from typing import Any, Self, Tuple

# A vector-like operand: a gacalc vector, a tuple, or any object providing
# two (or three) coordinates -- whatever pygame would accept.
VectorLike = Any


_VIRTUALS = {
    "topleft",
    "topright",
    "bottomleft",
    "bottomright",
    "midtop",
    "midbottom",
    "midleft",
    "midright",
    "center",
    "centerx",
    "centery",
    "left",
    "right",
    "top",
    "bottom",
    "width",
    "height",
    "size",
    "w",
    "h",
    "x",
    "y",
}


class Rect:
    """A small ``pygame.Rect`` work-alike (the subset the games touch).

    Exposes the virtual corner/edge attributes (settable, so ``rect.center =
    ...`` repositions), ``colliderect``/``collidepoint``/``contains``, and
    ``move``/``inflate``.

    Coordinates are **integers**, like ``pygame.Rect`` (assignments are
    truncated toward zero) -- the games rely on this, e.g. ``randint(rect.top,
    rect.bottom)`` needs ints, and pgzero/pygame collision is integer-pixel.
    The float-coordinate variant pgzero calls ``ZRect`` -- used by :class:`Actor`
    to keep sub-pixel positions -- is the :class:`ZRect` subclass below, which
    overrides only the coordinate coercion.
    """

    @staticmethod
    def _coord(v: float) -> float:
        # pygame.Rect stores integer coordinates, truncated toward zero.
        return int(v)

    def __init__(self, *args: Any) -> None:
        if len(args) == 1:  # Rect(other) or Rect((x,y,w,h))
            a = args[0]
            if isinstance(a, Rect):
                x, y, w, h = a.x, a.y, a.width, a.height
            else:
                x, y, w, h = a
        elif len(args) == 2:  # Rect((x,y),(w,h))
            (x, y), (w, h) = args
        else:
            x, y, w, h = args
        # Assign through the coercing properties so Rect truncates to int and
        # ZRect keeps float -- every other coordinate write funnels here too.
        self.x = x
        self.y = y
        self.width = w
        self.height = h

    # backing storage + coordinate coercion ----------------------------------
    # x/y/width/height are properties so that *every* coordinate write (here,
    # the edge/corner setters, move_ip, ...) is coerced by ``_coord`` in one
    # place -- int for Rect, float for ZRect.
    @property
    def x(self) -> float:
        return self._x

    @x.setter
    def x(self, v: float) -> None:
        self._x = self._coord(v)

    @property
    def y(self) -> float:
        return self._y

    @y.setter
    def y(self, v: float) -> None:
        self._y = self._coord(v)

    @property
    def width(self) -> float:
        return self._w

    @width.setter
    def width(self, v: float) -> None:
        self._w = self._coord(v)

    @property
    def height(self) -> float:
        return self._h

    @height.setter
    def height(self, v: float) -> None:
        self._h = self._coord(v)

    # primary edges -----------------------------------------------------------
    @property
    def left(self) -> float:
        return self.x

    @left.setter
    def left(self, v: float) -> None:
        self.x = v

    @property
    def top(self) -> float:
        return self.y

    @top.setter
    def top(self, v: float) -> None:
        self.y = v

    @property
    def right(self) -> float:
        return self.x + self.width

    @right.setter
    def right(self, v: float) -> None:
        self.x = v - self.width

    @property
    def bottom(self) -> float:
        return self.y + self.height

    @bottom.setter
    def bottom(self, v: float) -> None:
        self.y = v - self.height

    @property
    def centerx(self) -> float:
        return self._coord(self.x + self.width / 2)

    @centerx.setter
    def centerx(self, v: float) -> None:
        self.x = v - self.width / 2

    @property
    def centery(self) -> float:
        return self._coord(self.y + self.height / 2)

    @centery.setter
    def centery(self, v: float) -> None:
        self.y = v - self.height / 2

    @property
    def w(self) -> float:
        return self.width

    @w.setter
    def w(self, v: float) -> None:
        self.width = v

    @property
    def h(self) -> float:
        return self.height

    @h.setter
    def h(self, v: float) -> None:
        self.height = v

    @property
    def size(self) -> Tuple[float, float]:
        return (self.width, self.height)

    @size.setter
    def size(self, v: Any) -> None:
        self.width, self.height = v

    # corner / mid pairs ------------------------------------------------------
    def _pair(self, hx: str, vy: str) -> Tuple[float, float]:
        return (getattr(self, hx), getattr(self, vy))

    def _set_pair(self, hx: str, vy: str, val: Any) -> None:
        setattr(self, hx, val[0])
        setattr(self, vy, val[1])

    @property
    def topleft(self) -> Tuple[float, float]:
        return (self.left, self.top)

    @topleft.setter
    def topleft(self, v: Any) -> None:
        self._set_pair("left", "top", v)

    @property
    def topright(self) -> Tuple[float, float]:
        return (self.right, self.top)

    @topright.setter
    def topright(self, v: Any) -> None:
        self._set_pair("right", "top", v)

    @property
    def bottomleft(self) -> Tuple[float, float]:
        return (self.left, self.bottom)

    @bottomleft.setter
    def bottomleft(self, v: Any) -> None:
        self._set_pair("left", "bottom", v)

    @property
    def bottomright(self) -> Tuple[float, float]:
        return (self.right, self.bottom)

    @bottomright.setter
    def bottomright(self, v: Any) -> None:
        self._set_pair("right", "bottom", v)

    @property
    def center(self) -> Tuple[float, float]:
        return (self.centerx, self.centery)

    @center.setter
    def center(self, v: Any) -> None:
        self._set_pair("centerx", "centery", v)

    @property
    def midtop(self) -> Tuple[float, float]:
        return (self.centerx, self.top)

    @midtop.setter
    def midtop(self, v: Any) -> None:
        self._set_pair("centerx", "top", v)

    @property
    def midbottom(self) -> Tuple[float, float]:
        return (self.centerx, self.bottom)

    @midbottom.setter
    def midbottom(self, v: Any) -> None:
        self._set_pair("centerx", "bottom", v)

    @property
    def midleft(self) -> Tuple[float, float]:
        return (self.left, self.centery)

    @midleft.setter
    def midleft(self, v: Any) -> None:
        self._set_pair("left", "centery", v)

    @property
    def midright(self) -> Tuple[float, float]:
        return (self.right, self.centery)

    @midright.setter
    def midright(self, v: Any) -> None:
        self._set_pair("right", "centery", v)

    # queries -----------------------------------------------------------------
    def collidepoint(self, *p: Any) -> bool:
        px, py = p[0] if len(p) == 1 else p
        return self.left <= px < self.right and self.top <= py < self.bottom

    def colliderect(self, o: Rect) -> bool:
        return (
            self.left < o.right
            and self.right > o.left
            and self.top < o.bottom
            and self.bottom > o.top
        )

    def contains(self, o: Rect) -> bool:
        return (
            self.left <= o.left
            and self.right >= o.right
            and self.top <= o.top
            and self.bottom >= o.bottom
        )

    def move(self, dx: float, dy: float) -> Self:
        return self.__class__(self.x + dx, self.y + dy, self.width, self.height)

    def move_ip(self, dx: float, dy: float) -> None:
        self.x += dx
        self.y += dy

    def inflate(self, dx: float, dy: float) -> Self:
        return self.__class__(
            self.x - dx / 2, self.y - dy / 2, self.width + dx, self.height + dy
        )

    def copy(self) -> Self:
        return self.__class__(self.x, self.y, self.width, self.height)

    def __iter__(self) -> Iterator[float]:
        return iter((self.x, self.y, self.width, self.height))

    def __repr__(self) -> str:
        return "%s(%g, %g, %g, %g)" % (
            type(self).__name__,
            self.x,
            self.y,
            self.width,
            self.height,
        )


class ZRect(Rect):
    """pgzero's float-coordinate rectangle (``pgzero.rect.ZRect``).

    Identical to :class:`Rect` except coordinates keep sub-pixel precision
    instead of truncating to int. :class:`~pgzero_gl.actor.Actor` stores its
    anchor position in a ``ZRect`` so movement at non-integer speeds doesn't
    drift; games that want integer pygame-rect semantics use :class:`Rect`.
    """

    @staticmethod
    def _coord(v: float) -> float:
        return float(v)
