# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- a minimal pygame.Rect / pgzero ZRect work-alike.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# geometry.py -- the games use Rect for collisions and as a positioning helper.
# This is a small float-friendly rectangle exposing the subset of the
# pygame.Rect API they actually touch (the virtual corner/edge attributes,
# colliderect, collidepoint, contains, move, inflate).

import math


class Vector2:
    """A small pygame.math.Vector2 work-alike (the subset the games use)."""

    __slots__ = ("x", "y")

    def __init__(self, x=0.0, y=0.0):
        if hasattr(x, "__len__"):
            x, y = x
        elif hasattr(x, "x") and hasattr(x, "y"):
            x, y = x.x, x.y
        self.x = float(x)
        self.y = float(y)

    def __iter__(self):
        return iter((self.x, self.y))

    def __getitem__(self, i):
        return (self.x, self.y)[i]

    def __len__(self):
        return 2

    def __repr__(self):
        return "Vector2(%g, %g)" % (self.x, self.y)

    def __eq__(self, o):
        return self.x == o[0] and self.y == o[1]

    def __add__(self, o):
        return Vector2(self.x + o[0], self.y + o[1])

    __radd__ = __add__

    def __sub__(self, o):
        return Vector2(self.x - o[0], self.y - o[1])

    def __rsub__(self, o):
        return Vector2(o[0] - self.x, o[1] - self.y)

    def __mul__(self, s):
        return Vector2(self.x * s, self.y * s)

    __rmul__ = __mul__

    def __truediv__(self, s):
        return Vector2(self.x / s, self.y / s)

    def __neg__(self):
        return Vector2(-self.x, -self.y)

    def length(self):
        return math.hypot(self.x, self.y)

    def length_squared(self):
        return self.x * self.x + self.y * self.y

    def magnitude(self):
        return self.length()

    def dot(self, o):
        return self.x * o[0] + self.y * o[1]

    def normalize(self):
        n = self.length()
        return Vector2(self.x / n, self.y / n) if n else Vector2(0, 0)

    def normalize_ip(self):
        n = self.length()
        if n:
            self.x /= n
            self.y /= n

    def distance_to(self, o):
        return math.hypot(self.x - o[0], self.y - o[1])

    def rotate(self, degrees):
        # pygame Vector2.rotate is counter-clockwise in screen space (y down).
        t = math.radians(degrees)
        c, s = math.cos(t), math.sin(t)
        return Vector2(self.x * c - self.y * s, self.x * s + self.y * c)

    def copy(self):
        return Vector2(self.x, self.y)


class Vector3:
    """A small pygame.math.Vector3 work-alike (leadingedge's pseudo-3D road)."""

    __slots__ = ("x", "y", "z")

    def __init__(self, x=0.0, y=0.0, z=0.0):
        if hasattr(x, "__len__"):
            x, y, z = x
        elif hasattr(x, "z"):
            x, y, z = x.x, x.y, x.z
        self.x, self.y, self.z = float(x), float(y), float(z)

    def __iter__(self):
        return iter((self.x, self.y, self.z))

    def __getitem__(self, i):
        return (self.x, self.y, self.z)[i]

    def __len__(self):
        return 3

    def __repr__(self):
        return "Vector3(%g, %g, %g)" % (self.x, self.y, self.z)

    def __eq__(self, o):
        return self.x == o[0] and self.y == o[1] and self.z == o[2]

    def __add__(self, o):
        return Vector3(self.x + o[0], self.y + o[1], self.z + o[2])

    __radd__ = __add__

    def __sub__(self, o):
        return Vector3(self.x - o[0], self.y - o[1], self.z - o[2])

    def __rsub__(self, o):
        return Vector3(o[0] - self.x, o[1] - self.y, o[2] - self.z)

    def __mul__(self, s):
        return Vector3(self.x * s, self.y * s, self.z * s)

    __rmul__ = __mul__

    def __truediv__(self, s):
        return Vector3(self.x / s, self.y / s, self.z / s)

    def __neg__(self):
        return Vector3(-self.x, -self.y, -self.z)

    def length(self):
        return math.sqrt(self.x ** 2 + self.y ** 2 + self.z ** 2)

    def length_squared(self):
        return self.x ** 2 + self.y ** 2 + self.z ** 2

    def dot(self, o):
        return self.x * o[0] + self.y * o[1] + self.z * o[2]

    def cross(self, o):
        return Vector3(
            self.y * o[2] - self.z * o[1],
            self.z * o[0] - self.x * o[2],
            self.x * o[1] - self.y * o[0],
        )

    def normalize(self):
        n = self.length()
        return Vector3(self.x / n, self.y / n, self.z / n) if n else Vector3()

    def distance_to(self, o):
        return math.sqrt((self.x - o[0]) ** 2 + (self.y - o[1]) ** 2 + (self.z - o[2]) ** 2)

    def copy(self):
        return Vector3(self.x, self.y, self.z)


_VIRTUALS = {
    "topleft", "topright", "bottomleft", "bottomright",
    "midtop", "midbottom", "midleft", "midright",
    "center", "centerx", "centery",
    "left", "right", "top", "bottom",
    "width", "height", "size", "w", "h", "x", "y",
}


class Rect:
    def __init__(self, *args):
        if len(args) == 1:  # Rect(other) or Rect((x,y,w,h))
            a = args[0]
            if isinstance(a, Rect):
                x, y, w, h = a.x, a.y, a.width, a.height
            else:
                x, y, w, h = a
        elif len(args) == 2:  # Rect((x,y),(w,h))
            (x, y), (w, h) = args
        else:
            x, y, w, h = args
        self.x = float(x)
        self.y = float(y)
        self.width = float(w)
        self.height = float(h)

    # primary edges -----------------------------------------------------------
    @property
    def left(self):
        return self.x

    @left.setter
    def left(self, v):
        self.x = v

    @property
    def top(self):
        return self.y

    @top.setter
    def top(self, v):
        self.y = v

    @property
    def right(self):
        return self.x + self.width

    @right.setter
    def right(self, v):
        self.x = v - self.width

    @property
    def bottom(self):
        return self.y + self.height

    @bottom.setter
    def bottom(self, v):
        self.y = v - self.height

    @property
    def centerx(self):
        return self.x + self.width / 2

    @centerx.setter
    def centerx(self, v):
        self.x = v - self.width / 2

    @property
    def centery(self):
        return self.y + self.height / 2

    @centery.setter
    def centery(self, v):
        self.y = v - self.height / 2

    @property
    def w(self):
        return self.width

    @w.setter
    def w(self, v):
        self.width = v

    @property
    def h(self):
        return self.height

    @h.setter
    def h(self, v):
        self.height = v

    @property
    def size(self):
        return (self.width, self.height)

    @size.setter
    def size(self, v):
        self.width, self.height = v

    # corner / mid pairs ------------------------------------------------------
    def _pair(self, hx, vy):
        return (getattr(self, hx), getattr(self, vy))

    def _set_pair(self, hx, vy, val):
        setattr(self, hx, val[0])
        setattr(self, vy, val[1])

    @property
    def topleft(self):
        return (self.left, self.top)

    @topleft.setter
    def topleft(self, v):
        self._set_pair("left", "top", v)

    @property
    def topright(self):
        return (self.right, self.top)

    @topright.setter
    def topright(self, v):
        self._set_pair("right", "top", v)

    @property
    def bottomleft(self):
        return (self.left, self.bottom)

    @bottomleft.setter
    def bottomleft(self, v):
        self._set_pair("left", "bottom", v)

    @property
    def bottomright(self):
        return (self.right, self.bottom)

    @bottomright.setter
    def bottomright(self, v):
        self._set_pair("right", "bottom", v)

    @property
    def center(self):
        return (self.centerx, self.centery)

    @center.setter
    def center(self, v):
        self._set_pair("centerx", "centery", v)

    @property
    def midtop(self):
        return (self.centerx, self.top)

    @midtop.setter
    def midtop(self, v):
        self._set_pair("centerx", "top", v)

    @property
    def midbottom(self):
        return (self.centerx, self.bottom)

    @midbottom.setter
    def midbottom(self, v):
        self._set_pair("centerx", "bottom", v)

    @property
    def midleft(self):
        return (self.left, self.centery)

    @midleft.setter
    def midleft(self, v):
        self._set_pair("left", "centery", v)

    @property
    def midright(self):
        return (self.right, self.centery)

    @midright.setter
    def midright(self, v):
        self._set_pair("right", "centery", v)

    # queries -----------------------------------------------------------------
    def collidepoint(self, *p):
        px, py = p[0] if len(p) == 1 else p
        return self.left <= px < self.right and self.top <= py < self.bottom

    def colliderect(self, o):
        return (
            self.left < o.right
            and self.right > o.left
            and self.top < o.bottom
            and self.bottom > o.top
        )

    def contains(self, o):
        return (
            self.left <= o.left
            and self.right >= o.right
            and self.top <= o.top
            and self.bottom >= o.bottom
        )

    def move(self, dx, dy):
        return Rect(self.x + dx, self.y + dy, self.width, self.height)

    def move_ip(self, dx, dy):
        self.x += dx
        self.y += dy

    def inflate(self, dx, dy):
        return Rect(
            self.x - dx / 2, self.y - dy / 2, self.width + dx, self.height + dy
        )

    def copy(self):
        return Rect(self.x, self.y, self.width, self.height)

    def __iter__(self):
        return iter((self.x, self.y, self.width, self.height))

    def __repr__(self):
        return "Rect(%g, %g, %g, %g)" % (self.x, self.y, self.width, self.height)
