# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- keyboard input, backed by GLFW.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# input.py -- reproduce pgzero's `keyboard` object (boolean attribute access:
# `keyboard.space`, `keyboard.left`, ...) and the `keys` constants used by the
# on_key_down(key) hook.  Both are keyed on GLFW key codes; the runner feeds key
# events in via _press/_release.

import glfw

# pgzero attribute name -> GLFW key code.
_NAME_TO_KEY = {}


def _register():
    # letters a-z, digits 0-9
    for ch in "abcdefghijklmnopqrstuvwxyz":
        _NAME_TO_KEY[ch] = getattr(glfw, "KEY_" + ch.upper())
    for d in "0123456789":
        _NAME_TO_KEY["k_" + d] = getattr(glfw, "KEY_" + d)
        _NAME_TO_KEY[d] = getattr(glfw, "KEY_" + d)
    _NAME_TO_KEY.update(
        {
            "space": glfw.KEY_SPACE,
            "up": glfw.KEY_UP,
            "down": glfw.KEY_DOWN,
            "left": glfw.KEY_LEFT,
            "right": glfw.KEY_RIGHT,
            "return": glfw.KEY_ENTER,
            "enter": glfw.KEY_ENTER,
            "escape": glfw.KEY_ESCAPE,
            "tab": glfw.KEY_TAB,
            "backspace": glfw.KEY_BACKSPACE,
            "lshift": glfw.KEY_LEFT_SHIFT,
            "rshift": glfw.KEY_RIGHT_SHIFT,
            "lctrl": glfw.KEY_LEFT_CONTROL,
            "rctrl": glfw.KEY_RIGHT_CONTROL,
            "lalt": glfw.KEY_LEFT_ALT,
            "ralt": glfw.KEY_RIGHT_ALT,
        }
    )


_register()


class Keyboard:
    """`keyboard.<name>` is True while that key is held."""

    def __init__(self):
        self._pressed = set()

    def _press(self, key):
        self._pressed.add(key)

    def _release(self, key):
        self._pressed.discard(key)

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        code = _NAME_TO_KEY.get(name.lower())
        if code is None:
            return False
        return code in self._pressed

    def __getitem__(self, code):
        return code in self._pressed


class _Keys:
    """pgzero `keys.SPACE` etc.  Values are GLFW codes, matching what the runner
    passes to on_key_down(key)."""

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        code = _NAME_TO_KEY.get(name.lower())
        if code is None:
            raise AttributeError("Unknown key constant: %s" % name)
        return code


keyboard = Keyboard()
keys = _Keys()
