# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- gamepad support, mapping pygame.joystick onto GLFW.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol2
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# joystick.py -- the Vol 2 games read gamepads via pygame.joystick.  We expose
# the same small API backed by GLFW's joystick functions.  It is best-effort:
# with no controller attached every query returns neutral values, so the games
# remain fully playable on the keyboard.  (Gamepad behaviour can't be verified
# in the headless build container -- that's for on-hardware testing.)

import glfw

from . import context

# GLFW hat bit flags -> pygame (x, y) with y up = +1 (pygame convention).
_HAT_UP = 1
_HAT_RIGHT = 2
_HAT_DOWN = 4
_HAT_LEFT = 8


def get_count():
    # GLFW must be initialized first.  Game modules call setup_joystick_controls()
    # at import time (before the window/loop exist); querying GLFW then returns
    # garbage, so report "no joysticks" until the runner has init'd GLFW.
    if not context.glfw_ready:
        return 0
    n = 0
    for jid in range(16):
        try:
            if glfw.joystick_present(jid):
                n += 1
        except Exception:
            pass
    return n


def get_init():
    return True


def init():
    pass


class Joystick:
    def __init__(self, index):
        self.index = index  # GLFW joystick id (0-based), matches pygame index

    def init(self):
        pass

    def get_init(self):
        return True

    def get_id(self):
        return self.index

    def get_name(self):
        try:
            name = glfw.get_joystick_name(self.index)
            return name.decode() if isinstance(name, bytes) else (name or "")
        except Exception:
            return ""

    def _axes(self):
        if not context.glfw_ready:
            return []
        try:
            return list(glfw.get_joystick_axes(self.index) or [])
        except Exception:
            return []

    def _buttons(self):
        if not context.glfw_ready:
            return []
        try:
            return list(glfw.get_joystick_buttons(self.index) or [])
        except Exception:
            return []

    def _hats(self):
        if not context.glfw_ready:
            return []
        try:
            return list(glfw.get_joystick_hats(self.index) or [])
        except Exception:
            return []

    def get_numaxes(self):
        return len(self._axes())

    def get_axis(self, i):
        a = self._axes()
        try:
            return float(a[i]) if i < len(a) else 0.0
        except (TypeError, ValueError):
            return 0.0

    def get_numbuttons(self):
        return len(self._buttons())

    def get_button(self, i):
        b = self._buttons()
        if i >= len(b):
            return 0
        try:
            return int(b[i])
        except (TypeError, ValueError):
            return 1 if b[i] else 0

    def get_numhats(self):
        return len(self._hats())

    def get_hat(self, i):
        h = self._hats()
        if i >= len(h):
            return (0, 0)
        v = h[i]
        x = (1 if v & _HAT_RIGHT else 0) - (1 if v & _HAT_LEFT else 0)
        y = (1 if v & _HAT_UP else 0) - (1 if v & _HAT_DOWN else 0)
        return (x, y)
