# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- a minimal pygame.mask work-alike.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol2
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# mask.py -- avenger builds a collision mask from its terrain image and queries
# per-pixel opacity (get_at).  We back the mask with the image's alpha channel
# (which we already keep on the CPU), so this needs no GL.

import numpy as np


class Mask:
    def __init__(self, alpha):
        self._a = alpha  # HxW bool/uint8: True where opaque
        self.height, self.width = alpha.shape[0], alpha.shape[1]

    def get_size(self):
        return (self.width, self.height)

    def get_at(self, pos):
        x, y = int(pos[0]), int(pos[1])
        if 0 <= x < self.width and 0 <= y < self.height:
            return 1 if self._a[y, x] else 0
        return 0

    def overlap(self, other, offset):
        # Bounding-box-clipped per-pixel AND of the two masks (rare; provided for
        # completeness).  Returns a colliding point or None.
        ox, oy = int(offset[0]), int(offset[1])
        for y in range(max(0, oy), min(self.height, oy + other.height)):
            for x in range(max(0, ox), min(self.width, ox + other.width)):
                if self._a[y, x] and other._a[y - oy, x - ox]:
                    return (x, y)
        return None


def from_surface(surface, threshold=127):
    """Build a Mask from an Image/Surface, marking pixels with alpha > threshold."""
    return Mask(surface.rgba[..., 3] > threshold)
