# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- fixed-function OpenGL 1.x renderer backend.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# renderer_gl1.py -- a drop-in alternative to renderer.Renderer that uses the
# OpenGL 1.x FIXED-FUNCTION pipeline (glOrtho + glBegin/glEnd immediate mode +
# fixed-function texturing) instead of 3.3 core + shaders.  Same interface, so
# the rest of the shim is unchanged; selected with PGZERO_GL=1 (see runner.py).
#
# Why: runs on old / software / compat-only GL stacks where a 3.3 core context
# isn't available -- and it's the exact fixed-function era the book introduces at
# demo19 (glMatrixMode / glOrtho / glBegin / glEnable(GL_TEXTURE_2D)).  The 3.3
# renderer and this one draw the same pixels; compare them with _smoketest.py.
#
# Targets OpenGL 1.4/1.5 (really anything >= 1.1: textures + immediate mode).
# Image/Surface .gl_texture() upload via glGenTextures/glTexImage2D, which are
# 1.x-compatible and need no VAO -- so nothing else changes.

import numpy as np
import OpenGL.GL as GL

from .renderer import _rgba  # shared colour normaliser


class Renderer1x:
    def __init__(self, width, height):
        self.width = width
        self.height = height
        self.fb_width = width
        self.fb_height = height
        GL.glEnable(GL.GL_BLEND)
        GL.glBlendFunc(GL.GL_SRC_ALPHA, GL.GL_ONE_MINUS_SRC_ALPHA)
        GL.glDisable(GL.GL_DEPTH_TEST)
        # Fixed-function texture env: texture * glColor (matches the 3.3 path's
        # frag = texture * uTint).
        GL.glTexEnvi(GL.GL_TEXTURE_ENV, GL.GL_TEXTURE_ENV_MODE, GL.GL_MODULATE)

    # -- frame ----------------------------------------------------------------
    def begin_frame(self, fb_width=None, fb_height=None):
        if fb_width:
            self.fb_width = fb_width
            self.fb_height = fb_height
        GL.glDisable(GL.GL_SCISSOR_TEST)
        GL.glViewport(0, 0, self.fb_width, self.fb_height)
        GL.glClearColor(0.0, 0.0, 0.0, 1.0)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)
        # Pixel-space projection: (0,0) top-left .. (W,H) bottom-right.
        GL.glMatrixMode(GL.GL_PROJECTION)
        GL.glLoadIdentity()
        GL.glOrtho(0.0, self.width, self.height, 0.0, -1.0, 1.0)
        GL.glMatrixMode(GL.GL_MODELVIEW)
        GL.glLoadIdentity()

    # -- sprites --------------------------------------------------------------
    def draw_image(
        self, image, topleft, angle=0.0, anchor=None, tint=(1.0, 1.0, 1.0, 1.0), src=None
    ):
        tx, ty = topleft
        if src is not None:
            sx, sy, sw, sh = src
            w, h = sw, sh
            u0, v0 = sx / image.width, sy / image.height
            u1, v1 = (sx + sw) / image.width, (sy + sh) / image.height
        else:
            w, h = image.width, image.height
            u0, v0, u1, v1 = 0.0, 0.0, 1.0, 1.0

        GL.glEnable(GL.GL_TEXTURE_2D)
        GL.glBindTexture(GL.GL_TEXTURE_2D, image.gl_texture())
        GL.glColor4f(*_rgba(tint))

        GL.glPushMatrix()
        if angle:
            ax, ay = anchor if anchor is not None else (tx + w * 0.5, ty + h * 0.5)
            GL.glTranslatef(ax, ay, 0.0)
            # -angle to match the 3.3 renderer's y-down rotation convention.
            GL.glRotatef(-angle, 0.0, 0.0, 1.0)
            GL.glTranslatef(-ax, -ay, 0.0)
        GL.glTranslatef(tx, ty, 0.0)
        GL.glScalef(w, h, 1.0)
        GL.glBegin(GL.GL_QUADS)
        GL.glTexCoord2f(u0, v0); GL.glVertex2f(0.0, 0.0)
        GL.glTexCoord2f(u1, v0); GL.glVertex2f(1.0, 0.0)
        GL.glTexCoord2f(u1, v1); GL.glVertex2f(1.0, 1.0)
        GL.glTexCoord2f(u0, v1); GL.glVertex2f(0.0, 1.0)
        GL.glEnd()
        GL.glPopMatrix()

    # -- flat colour ----------------------------------------------------------
    def fill(self, color):
        c = _rgba(color)
        GL.glClearColor(c[0], c[1], c[2], c[3])
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)

    def _flat(self, verts, color, mode):
        GL.glDisable(GL.GL_TEXTURE_2D)
        GL.glColor4f(*_rgba(color))
        GL.glBegin(mode)
        for x, y in verts:
            GL.glVertex2f(float(x), float(y))
        GL.glEnd()

    def filled_rect(self, x, y, w, h, color):
        self._flat(
            [(x, y), (x + w, y), (x + w, y + h), (x, y + h)], color, GL.GL_QUADS
        )

    def rect(self, x, y, w, h, color):
        self._flat(
            [(x, y), (x + w, y), (x + w, y + h), (x, y + h)], color, GL.GL_LINE_LOOP
        )

    def line(self, start, end, color):
        self._flat([start, end], color, GL.GL_LINES)

    def polygon(self, points, color, filled):
        mode = GL.GL_POLYGON if filled else GL.GL_LINE_LOOP
        self._flat([(p[0], p[1]) for p in points], color, mode)

    def circle(self, pos, radius, color, filled):
        cx, cy = pos
        n = 48
        pts = []
        if filled:
            pts.append((cx, cy))
        for i in range(n + 1):
            a = 2.0 * np.pi * i / n
            pts.append((cx + radius * np.cos(a), cy + radius * np.sin(a)))
        self._flat(pts, color, GL.GL_TRIANGLE_FAN if filled else GL.GL_LINE_STRIP)

    # -- scissor (screen.surface.set_clip) ------------------------------------
    def set_clip(self, rect):
        if rect is None:
            GL.glDisable(GL.GL_SCISSOR_TEST)
            return
        x, y, w, h = rect
        sx = self.fb_width / self.width
        sy = self.fb_height / self.height
        GL.glEnable(GL.GL_SCISSOR_TEST)
        GL.glScissor(
            int(x * sx), int(self.fb_height - (y + h) * sy), int(w * sx), int(h * sy)
        )
