# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- image/sound resource loaders.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# resources.py -- reproduce PyGame Zero's `images` and `sounds` objects.  In
# pgzero you write `Actor("ship")` or `sounds.explosion.play()` and it loads
# images/ship.png / sounds/explosion.ogg lazily, by attribute access, cached.
#
# Key difference from pgzero: images decode to a CPU RGBA array immediately (so
# width/height and pixel masks are available even before the window exists), but
# the GL texture is uploaded lazily on first draw -- because game objects are
# routinely constructed at import time, before the GL context exists.

import os

import numpy as np
import OpenGL.GL as GL
from PIL import Image as PILImage

from . import context
from . import audio


class Image:
    """A loaded image: CPU pixels now, GL texture on first draw."""

    def __init__(self, path):
        self.path = path
        # Decode with Pillow + convert("RGBA").  This correctly turns palette
        # (mode "P") transparency and grayscale/LA into a real alpha channel --
        # imageio drops palette transparency (returns 3-channel RGB), which made
        # transparent sprite backgrounds render as opaque white boxes.
        arr = np.array(PILImage.open(path).convert("RGBA"))
        self.rgba = np.ascontiguousarray(arr.astype(np.uint8))
        self.height, self.width = self.rgba.shape[0], self.rgba.shape[1]
        self._tex = None

    @classmethod
    def from_rgba(cls, arr):
        """Build an Image directly from an HxWx4 uint8 array (used by text.py)."""
        obj = cls.__new__(cls)
        obj.path = None
        obj.rgba = np.ascontiguousarray(arr.astype(np.uint8))
        obj.height, obj.width = obj.rgba.shape[0], obj.rgba.shape[1]
        obj._tex = None
        return obj

    # pgzero/pygame Surface-compatible accessors used by some games.
    def get_width(self):
        return self.width

    def get_height(self):
        return self.height

    def get_size(self):
        return (self.width, self.height)

    def get_rect(self, **kwargs):
        from .geometry import Rect

        r = Rect(0, 0, self.width, self.height)
        for k, v in kwargs.items():
            setattr(r, k, v)
        return r

    def gl_texture(self):
        if self._tex is None:
            context.require_renderer()
            self._tex = GL.glGenTextures(1)
            GL.glBindTexture(GL.GL_TEXTURE_2D, self._tex)
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_WRAP_S, GL.GL_CLAMP_TO_EDGE
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_WRAP_T, GL.GL_CLAMP_TO_EDGE
            )
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGBA,
                self.width,
                self.height,
                0,
                GL.GL_RGBA,
                GL.GL_UNSIGNED_BYTE,
                self.rgba,
            )
        return self._tex


class _Loader:
    """Attribute/`getattr` access to a resource folder, à la pgzero.

    `images.foo` and `getattr(images, "foo")` both load <root>/<subdir>/foo.<ext>.
    Results are cached.  The `name + str(n)` pattern (e.g. getattr(sounds, "hit0"))
    works because it's just attribute access with a computed name.
    """

    def __init__(self, subdir, extns, make):
        self._subdir = subdir
        self._extns = extns
        self._make = make
        self._cache = {}

    def _path(self, name):
        base = os.path.join(context.get_asset_root(), self._subdir, name)
        if os.path.isfile(base):
            return base
        for ext in self._extns:
            p = base + "." + ext
            if os.path.exists(p):
                return p
        return None

    def load(self, name):
        if name in self._cache:
            return self._cache[name]
        p = self._path(name)
        if p is None:
            raise KeyError(
                "No %s found like %r in %s/" % (self._subdir[:-1], name, self._subdir)
            )
        res = self._cache[name] = self._make(p)
        return res

    def __getattr__(self, name):
        if name.startswith("_"):
            raise AttributeError(name)
        try:
            return self.load(name)
        except KeyError as e:
            raise AttributeError(*e.args) from None

    # A couple of games iterate the loaded sounds.
    def values(self):
        return self._cache.values()

    def clear(self):
        self._cache.clear()


images = _Loader("images", ["png", "gif", "jpg", "jpeg", "bmp"], Image)
sounds = _Loader("sounds", ["ogg", "wav", "oga"], audio.Sound)
