# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""The game loop / window -- pgzero's ``pgzrun.go()``, on GLFW + OpenGL.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

:func:`go` replaces pgzero's ``pgzrun.go()``. It reads ``WIDTH``/``HEIGHT``/
``TITLE``/``update``/``draw``/``on_*`` from the calling game module, opens a GL
window (3.3 core by default, or fixed-function 1.x under ``PGZERO_GL=1``), and
runs a fixed 60 Hz loop -- the games assume a fixed timestep, so most ``update``
functions take no ``dt`` (we pass one only if the signature accepts it).
"""

from __future__ import annotations

import os
import sys
import time
from typing import Any, Dict, Tuple

import glfw
import OpenGL.GL as GL

from . import context
from .input import keyboard


def _select_renderer() -> Tuple[type, bool]:
    """Pick the renderer backend (and whether it needs a legacy GL context).

    Reads ``PGZERO_GL``; default = modern 3.3 core + shaders. Returns
    ``(renderer_class, legacy)``.
    """
    mode: str = os.environ.get("PGZERO_GL", "").lower()
    if mode in ("1", "gl1", "legacy", "1.4", "1.5", "fixed"):
        from .renderer_gl1 import Renderer1x

        return Renderer1x, True
    from .renderer import Renderer

    return Renderer, False


def _make_window(
    width: int, height: int, title: str, legacy: bool = False
) -> Any:
    """Init GLFW, create the GL window/context, and return the window handle."""
    if not glfw.init():
        raise RuntimeError("glfw.init() failed")
    context.glfw_ready = True
    if legacy:
        # Fixed-function: a compatibility (2.1) context exposes GL 1.x.
        glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 2)
        glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 1)
        glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_ANY_PROFILE)
    else:
        glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 3)
        glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 3)
        glfw.window_hint(glfw.OPENGL_PROFILE, glfw.OPENGL_CORE_PROFILE)
        glfw.window_hint(glfw.OPENGL_FORWARD_COMPAT, GL.GL_TRUE)
    win: Any = glfw.create_window(width, height, title, None, None)
    if not win:
        glfw.terminate()
        raise RuntimeError("glfw.create_window() failed")
    glfw.make_context_current(win)
    glfw.swap_interval(1)
    if not legacy:
        # macOS core profile requires a non-zero VAO bound at all times (see the
        # modelviewprojection demos' note); harmless elsewhere.  Not a GL 1.x call.
        GL.glBindVertexArray(GL.glGenVertexArrays(1))
    return win


def go(g: Dict[str, Any] | None = None) -> None:
    """Run the game whose globals are ``g`` (defaults to the caller's module)."""
    if g is None:
        g = sys._getframe(1).f_globals

    width: int = int(g.get("WIDTH", 800))
    height: int = int(g.get("HEIGHT", 600))
    title: str = g.get("TITLE", "Pygame Zero Game")

    # Assets live next to the game file.
    game_file = g.get("__file__")
    if game_file:
        context.asset_root = os.path.dirname(os.path.abspath(game_file))

    renderer_cls, legacy = _select_renderer()
    window: Any = _make_window(width=width, height=height, title=title, legacy=legacy)
    context.window = window
    context.renderer = renderer_cls(width, height)

    # Diagnostics for on-hardware verification: PGZERO_GL_INFO=1 prints which GL
    # backend + driver is actually in use (confirms real GPU vs software, and
    # which renderer path); PGZERO_MAX_FRAMES=N auto-closes after N frames so all
    # games can be smoke-tested in a loop without playing each by hand.
    if os.environ.get("PGZERO_GL_INFO"):
        print(
            "[pgzero_gl] backend=%s  GL_VERSION=%s  GL_RENDERER=%s"
            % (
                "gl1-fixedfunc" if legacy else "gl33-core",
                GL.glGetString(GL.GL_VERSION).decode(errors="replace"),
                GL.glGetString(GL.GL_RENDERER).decode(errors="replace"),
            )
        )
    _max_frames: int = int(os.environ.get("PGZERO_MAX_FRAMES", "0") or 0)

    update = g.get("update")
    draw = g.get("draw")
    on_key_down = g.get("on_key_down")
    on_key_up = g.get("on_key_up")

    update_takes_dt: bool = (
        update is not None and update.__code__.co_argcount >= 1
    )

    def key_cb(
        win: Any, key: int, scancode: int, action: int, mods: int
    ) -> None:
        if action == glfw.PRESS:
            keyboard._press(key)
            if on_key_down:
                _call_key_hook(hook=on_key_down, key=key, mods=mods)
        elif action == glfw.RELEASE:
            keyboard._release(key)
            if on_key_up:
                _call_key_hook(hook=on_key_up, key=key, mods=mods)

    glfw.set_key_callback(window, key_cb)

    frame: float = 1.0 / 60.0
    next_t: float = time.perf_counter()
    frame_count: int = 0
    try:
        while not glfw.window_should_close(window):
            glfw.poll_events()

            if update:
                update(frame) if update_takes_dt else update()

            fb_w, fb_h = glfw.get_framebuffer_size(window)
            context.renderer.begin_frame(fb_width=fb_w, fb_height=fb_h)
            if draw:
                draw()
            glfw.swap_buffers(window)

            frame_count += 1
            if _max_frames and frame_count >= _max_frames:
                break

            next_t += frame
            sleep: float = next_t - time.perf_counter()
            if sleep > 0:
                time.sleep(sleep)
            else:
                next_t = time.perf_counter()
    finally:
        glfw.terminate()


def _call_key_hook(hook: Any, key: int, mods: int) -> None:
    """Call a game's ``on_key_*`` hook, passing whichever of (key, mod) it declares.

    ``hook`` is a game function we introspect via ``__code__``, hence ``Any``.
    """
    # Pass whichever of (key, mod) the handler declares, like pgzero does.
    names = hook.__code__.co_varnames[: hook.__code__.co_argcount]
    kwargs: Dict[str, Any] = {}
    if "key" in names:
        kwargs["key"] = key
    if "mod" in names:
        kwargs["mod"] = mods
    hook(**kwargs)


def quit_game() -> None:
    """Ask the window to close, ending the game loop (pgzero's ``exit()``)."""
    if context.window is not None:
        glfw.set_window_should_close(context.window, True)
