# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""The ``screen`` object -- PyGame Zero's drawing surface.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

Reproduces pgzero's ``screen``: :meth:`Screen.blit`, :meth:`Screen.fill`, and the
``screen.draw.*`` primitives (:meth:`_Painter.text` / ``rect`` / ``filled_rect`` /
``line`` / ``circle`` / ...). Every method forwards to the active
:class:`pgzero_gl.renderer.Renderer`, so ``screen`` carries no state of its own --
it is a thin, stateless facade over the GL back end.

A small :class:`_Surface` covers the games that reach the raw pygame
``screen.surface`` for ``set_clip`` (-> ``glScissor``) and ``blit``.
"""

from __future__ import annotations

import typing
from collections.abc import Sequence
from typing import Any, Tuple, Union

from gacalc.g2 import Vector2

from . import context
from . import text as _text
from ._types import Color, Drawable, PointLike
from .geometry import Rect, _RectBase  # noqa: F401  # Rect kept for re-export
from .resources import images

# any rect flavor (int Rect / float ZRect)
RectLike = _RectBase[Any]  # any coordinate flavor (int Rect / float ZRect)


def _as_xy(pos: Union[PointLike, RectLike]) -> Tuple[float, float]:
    """Normalize a blit position -- a point-like or a rect (its topleft)."""
    if isinstance(pos, _RectBase):
        # ty resolves the constrained-TypeVar property through Any to
        # `object`; both coordinate flavors read fine as float.
        r = typing.cast("_RectBase[float]", pos)
        return (float(r.left), float(r.top))
    if isinstance(pos, Vector2):
        return (float(pos.x), float(pos.y))
    return (float(pos[0]), float(pos[1]))


class _Painter:
    """``screen.draw.*`` -- thin adapter onto the renderer's flat-colour drawing."""

    def text(self, *args: Any, **kwargs: Any) -> None:
        """Draw text (see :func:`pgzero_gl.text.draw` for the keyword options)."""
        _text.draw(*args, **kwargs)

    def rect(self, rect: RectLike, color: Color) -> None:
        """Draw the outline of ``rect`` in ``color``."""
        context.require_renderer().rect(
            x=rect.x, y=rect.y, w=rect.width, h=rect.height, color=color
        )

    def filled_rect(self, rect: RectLike, color: Color) -> None:
        """Draw ``rect`` filled with ``color``."""
        context.require_renderer().filled_rect(
            x=rect.x, y=rect.y, w=rect.width, h=rect.height, color=color
        )

    def line(self, start: PointLike, end: PointLike, color: Color) -> None:
        """Draw a line from ``start`` to ``end`` in ``color``."""
        context.require_renderer().line(start=start, end=end, color=color)

    def circle(self, pos: PointLike, radius: float, color: Color) -> None:
        """Draw the outline of a circle centred at ``pos``."""
        context.require_renderer().circle(
            pos=pos, radius=radius, color=color, filled=False
        )

    def filled_circle(
        self, pos: PointLike, radius: float, color: Color
    ) -> None:
        """Draw a filled circle centred at ``pos``."""
        context.require_renderer().circle(
            pos=pos, radius=radius, color=color, filled=True
        )


class _Surface:
    """Minimal stand-in for ``screen.surface`` (the raw pygame Surface).

    Only the operations the games use are implemented.
    """

    def set_clip(self, rect: RectLike | Sequence[float] | None) -> None:
        """Clip subsequent drawing to ``rect`` (``None`` clears the clip)."""
        context.require_renderer().set_clip(rect)

    def blit(
        self,
        image: Union[str, Drawable],
        pos: Union[PointLike, RectLike],
        area: RectLike | Sequence[float] | None = None,
    ) -> None:
        """Blit ``image`` (name or Image) at ``pos``; ``area`` is a sub-rect source."""
        img = images.load(image) if isinstance(image, str) else image
        src: tuple[Any, ...] | None = tuple(area) if area is not None else None
        context.require_renderer().draw_image(
            image=img, topleft=_as_xy(pos), src=src
        )

    def get_width(self) -> int:
        """Return the screen width in pixels."""
        return context.require_renderer().width

    def get_height(self) -> int:
        """Return the screen height in pixels."""
        return context.require_renderer().height

    def get_size(self) -> Tuple[int, int]:
        """Return ``(width, height)`` in pixels."""
        r = context.require_renderer()
        return (r.width, r.height)


class Screen:
    """pgzero's ``screen``: ``blit``/``fill`` plus the ``draw`` and ``surface`` facades."""

    def __init__(self) -> None:
        self.draw = _Painter()
        self.surface = _Surface()

    @property
    def width(self) -> int:
        """The screen width in pixels."""
        return context.require_renderer().width

    @property
    def height(self) -> int:
        """The screen height in pixels."""
        return context.require_renderer().height

    def bounds(self) -> Rect:
        """Return a :class:`Rect` covering the whole screen."""
        r = context.require_renderer()
        return Rect(0, 0, r.width, r.height)

    def clear(self) -> None:
        """Clear the screen to black."""
        context.require_renderer().fill((0, 0, 0))

    def fill(self, color: Color) -> None:
        """Fill the whole screen with ``color``."""
        context.require_renderer().fill(color)

    def blit(
        self, image: Union[str, Drawable], pos: Union[PointLike, RectLike]
    ) -> None:
        """Blit ``image`` (name or Image) at ``pos`` (a point or a Rect's topleft)."""
        img = images.load(image) if isinstance(image, str) else image
        context.require_renderer().draw_image(image=img, topleft=_as_xy(pos))


screen = Screen()
