# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""The ``screen`` object -- PyGame Zero's drawing surface.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

Reproduces pgzero's ``screen``: :meth:`Screen.blit`, :meth:`Screen.fill`, and the
``screen.draw.*`` primitives (:meth:`_Painter.text` / ``rect`` / ``filled_rect`` /
``line`` / ``circle`` / ...). Every method forwards to the active
:class:`pgzero_gl.renderer.Renderer`, so ``screen`` carries no state of its own --
it is a thin, stateless facade over the GL back end.

A small :class:`_Surface` covers the games that reach the raw pygame
``screen.surface`` for ``set_clip`` (-> ``glScissor``) and ``blit``.
"""

from __future__ import annotations

from typing import Any, Tuple

from . import context
from . import text as _text
from .geometry import Rect
from .resources import images


class _Painter:
    """``screen.draw.*`` -- thin adapter onto the renderer's flat-colour drawing."""

    def text(self, *args: Any, **kwargs: Any) -> None:
        """Draw text (see :func:`pgzero_gl.text.draw` for the keyword options)."""
        _text.draw(*args, **kwargs)

    def rect(self, rect: Rect, color: Any) -> None:
        """Draw the outline of ``rect`` in ``color``."""
        context.require_renderer().rect(
            x=rect.x, y=rect.y, w=rect.width, h=rect.height, color=color
        )

    def filled_rect(self, rect: Rect, color: Any) -> None:
        """Draw ``rect`` filled with ``color``."""
        context.require_renderer().filled_rect(
            x=rect.x, y=rect.y, w=rect.width, h=rect.height, color=color
        )

    def line(self, start: Any, end: Any, color: Any) -> None:
        """Draw a line from ``start`` to ``end`` in ``color``."""
        context.require_renderer().line(start=start, end=end, color=color)

    def circle(self, pos: Any, radius: float, color: Any) -> None:
        """Draw the outline of a circle centred at ``pos``."""
        context.require_renderer().circle(
            pos=pos, radius=radius, color=color, filled=False
        )

    def filled_circle(self, pos: Any, radius: float, color: Any) -> None:
        """Draw a filled circle centred at ``pos``."""
        context.require_renderer().circle(
            pos=pos, radius=radius, color=color, filled=True
        )


class _Surface:
    """Minimal stand-in for ``screen.surface`` (the raw pygame Surface).

    Only the operations the games use are implemented.
    """

    def set_clip(self, rect: Any) -> None:
        """Clip subsequent drawing to ``rect`` (``None`` clears the clip)."""
        context.require_renderer().set_clip(rect)

    def blit(self, image: Any, pos: Any, area: Any = None) -> None:
        """Blit ``image`` (name or Image) at ``pos``; ``area`` is a sub-rect source."""
        img = images.load(image) if isinstance(image, str) else image
        if hasattr(pos, "topleft"):
            pos = pos.topleft
        x, y = pos  # tuple OR gacalc vector (iterable pair)
        src: tuple[Any, ...] | None = tuple(area) if area is not None else None
        context.require_renderer().draw_image(
            image=img, topleft=(x, y), src=src
        )

    def get_width(self) -> int:
        """Return the screen width in pixels."""
        return context.require_renderer().width

    def get_height(self) -> int:
        """Return the screen height in pixels."""
        return context.require_renderer().height

    def get_size(self) -> Tuple[int, int]:
        """Return ``(width, height)`` in pixels."""
        r = context.require_renderer()
        return (r.width, r.height)


class Screen:
    """pgzero's ``screen``: ``blit``/``fill`` plus the ``draw`` and ``surface`` facades."""

    def __init__(self) -> None:
        self.draw = _Painter()
        self.surface = _Surface()

    @property
    def width(self) -> int:
        """The screen width in pixels."""
        return context.require_renderer().width

    @property
    def height(self) -> int:
        """The screen height in pixels."""
        return context.require_renderer().height

    def bounds(self) -> Rect:
        """Return a :class:`Rect` covering the whole screen."""
        r = context.require_renderer()
        return Rect(0, 0, r.width, r.height)

    def clear(self) -> None:
        """Clear the screen to black."""
        context.require_renderer().fill((0, 0, 0))

    def fill(self, color: Any) -> None:
        """Fill the whole screen with ``color``."""
        context.require_renderer().fill(color)

    def blit(self, image: Any, pos: Any) -> None:
        """Blit ``image`` (name or Image) at ``pos`` (a point or a Rect's topleft)."""
        img = images.load(image) if isinstance(image, str) else image
        # pos may be a Rect -> use its topleft
        if hasattr(pos, "topleft"):
            pos = pos.topleft
        x, y = pos  # tuple OR gacalc vector (iterable pair)
        context.require_renderer().draw_image(image=img, topleft=(x, y))


screen = Screen()
