# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- the `screen` object.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# screen.py -- PyGame Zero's drawing surface: screen.blit(name, pos),
# screen.fill(color), and screen.draw.{text,rect,filled_rect,line,circle,...}.
# A small `screen.surface` facade covers the games that reach the raw pygame
# surface for set_clip (-> glScissor) and blit.

from . import context
from . import text as _text


class _Painter:
    """screen.draw.* -- thin adapter onto the renderer's flat-colour drawing."""

    def text(self, *args, **kwargs):
        _text.draw(*args, **kwargs)

    def rect(self, rect, color):
        context.require_renderer().rect(rect.x, rect.y, rect.width, rect.height, color)

    def filled_rect(self, rect, color):
        context.require_renderer().filled_rect(
            rect.x, rect.y, rect.width, rect.height, color
        )

    def line(self, start, end, color):
        context.require_renderer().line(start, end, color)

    def circle(self, pos, radius, color):
        context.require_renderer().circle(pos, radius, color, filled=False)

    def filled_circle(self, pos, radius, color):
        context.require_renderer().circle(pos, radius, color, filled=True)


class _Surface:
    """Minimal stand-in for `screen.surface` (the raw pygame Surface).  Only the
    operations the games use are implemented."""

    def set_clip(self, rect):
        context.require_renderer().set_clip(rect)

    def blit(self, image, pos, area=None):
        from .resources import images

        img = images.load(image) if isinstance(image, str) else image
        if hasattr(pos, "topleft"):
            pos = pos.topleft
        src = tuple(area) if area is not None else None
        context.require_renderer().draw_image(img, pos, src=src)

    def get_width(self):
        return context.require_renderer().width

    def get_height(self):
        return context.require_renderer().height

    def get_size(self):
        r = context.require_renderer()
        return (r.width, r.height)


class Screen:
    def __init__(self):
        self.draw = _Painter()
        self.surface = _Surface()

    @property
    def width(self):
        return context.require_renderer().width

    @property
    def height(self):
        return context.require_renderer().height

    def bounds(self):
        from .geometry import Rect

        r = context.require_renderer()
        return Rect(0, 0, r.width, r.height)

    def clear(self):
        context.require_renderer().fill((0, 0, 0))

    def fill(self, color):
        context.require_renderer().fill(color)

    def blit(self, image, pos):
        from .resources import images

        img = images.load(image) if isinstance(image, str) else image
        # pos may be a Rect -> use its topleft
        if hasattr(pos, "topleft"):
            pos = pos.topleft
        context.require_renderer().draw_image(img, pos)


screen = Screen()
