# Copyright (c) 2026 William Emerison Six
#
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
#
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""``pygame.transform`` work-alikes (image scaling via PIL).

Formerly forged into the synthetic ``pygame`` module by ``_make_pygame``; now a
real module the games import directly (``from pgzero_gl import transform``).
"""

from __future__ import annotations

from typing import Any


def scale(surf: Any, size: Any, dest: Any = None) -> Any:
    import numpy as np
    from PIL import Image as PILImage

    from .resources import Image as GLImage

    pil = PILImage.fromarray(surf.rgba).resize(
        (max(1, int(size[0])), max(1, int(size[1]))),
        PILImage.Resampling.NEAREST,
    )
    return GLImage.from_rgba(np.array(pil.convert("RGBA")))


def smoothscale(surf: Any, size: Any, dest: Any = None) -> Any:
    import numpy as np
    from PIL import Image as PILImage

    from .resources import Image as GLImage

    pil = PILImage.fromarray(surf.rgba).resize(
        (max(1, int(size[0])), max(1, int(size[1]))),
        PILImage.Resampling.BILINEAR,
    )
    return GLImage.from_rgba(np.array(pil.convert("RGBA")))
