# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""Sound + music, without pygame -- PyGame Zero's ``sounds`` and ``music``.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

PyGame Zero gets audio from ``pygame.mixer`` (SDL). We deliberately avoid
pygame here (the project's host runs an SDL2-on-SDL3 shim that breaks SDL
audio) -- but we DO mirror pygame.mixer's architecture, because the games
were written against it: **one** output device opened once, every effect
decoded into an in-memory buffer at load, and N voices software-mixed in
the device's audio callback. Loops are gapless (buffer wraparound in the
mixer), fades are per-frame volume ramps inside the callback, and starting
or stopping a voice is a flag flip -- zero OS device operations after
startup.

History (2026-07-09): the previous backend (just_playback) opened a
SEPARATE miniaudio stream per voice. leadingedge's 41-sample engine
crossfade turned that into dozens of concurrent ALSA/PipeWire streams --
audibly clunky band changes (device start/stop clicks, plus decode on the
game thread per new band) and eventually a frozen game once the audio
client slots ran out and snd_pcm blocked the game thread. Root-cause
analysis: tasks/leadingedge-audio-clunk-and-freeze.md.

Audio remains BEST EFFORT: if miniaudio can't be imported or a device can't
be opened, every call becomes a no-op. The original games already wrap
sound in try/except, so silence never breaks gameplay -- and on-screen GL
is what gets human-verified here anyway (no audio device in the build
container).
"""

from __future__ import annotations

import os
import threading
from collections.abc import Generator, Iterator
from dataclasses import InitVar, dataclass, field
from typing import TYPE_CHECKING, Any, cast

import numpy as np
from numpy.typing import NDArray

from . import context

if TYPE_CHECKING:
    import miniaudio

#: interleaved float32 PCM at the mixing format
_PCM = NDArray[np.float32]

# the miniaudio module (or None if unavailable); Any so the sentinel and
# the module share a type
_ma: Any = None
_BACKEND: bool = False
try:
    import miniaudio as _miniaudio

    _ma = _miniaudio
    _BACKEND = True
except Exception:  # pragma: no cover - depends on runtime env
    pass


def available() -> bool:
    """Return whether an audio backend loaded (False -> all audio is a no-op)."""
    return _BACKEND


# One mixing format for everything; decode/stream converts to it.
_SAMPLE_RATE = 44100
_CHANNELS = 2

# pygame.mixer defaults to 8 mixing channels; cap concurrent voices per
# effect similarly so a rapidly-refired sound reuses its budget.
_MAX_VOICES_PER_SOUND = 8


@dataclass(slots=True)
class _Voice:
    """One playing instance inside the mixer: a position in a shared buffer
    (effects) or a pull-stream (music), plus volume/loop/fade state.

    Mutated under the engine lock; consumed by the mixer callback.
    """

    samples: _PCM | None
    stream: Iterator[Any] | None
    volume: float
    looping: bool
    #: fade-in duration; consumed by __post_init__ into the ramp fields
    fade_in_ms: InitVar[float]
    #: frame offset into ``samples`` (buffer voices only)
    pos: int = field(default=0, init=False)
    #: fade_gain multiplies volume and ramps by fade_step per FRAME
    fade_gain: float = field(default=1.0, init=False)
    fade_step: float = field(default=0.0, init=False)
    stop_when_faded: bool = field(default=False, init=False)
    done: bool = field(default=False, init=False)

    def __post_init__(self, fade_in_ms: float) -> None:
        if fade_in_ms > 0:
            self.fade_gain = 0.0
            self.fade_step = 1.0 / (_SAMPLE_RATE * fade_in_ms / 1000.0)

    def start_fadeout(self, ms: float) -> None:
        frames = max(_SAMPLE_RATE * ms / 1000.0, 1.0)
        self.fade_step = -self.fade_gain / frames
        self.stop_when_faded = True


class _Engine:
    """The single miniaudio PlaybackDevice + the software mixer feeding it."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._voices: list[_Voice] = []
        self._device: miniaudio.PlaybackDevice | None = None
        self._failed = False

    # -- device ---------------------------------------------------------
    def _ensure_device(self) -> bool:
        if self._device is not None:
            return True
        if self._failed or not _BACKEND:
            return False
        try:
            device = _ma.PlaybackDevice(
                output_format=_ma.SampleFormat.FLOAT32,
                nchannels=_CHANNELS,
                sample_rate=_SAMPLE_RATE,
            )
            gen = self._mixer()
            next(gen)  # prime the generator protocol
            # numpy arrays satisfy the buffer protocol miniaudio consumes;
            # its stubs only admit bytes/array.array, hence the cast.
            device.start(cast(Any, gen))
            self._device = device
            return True
        except Exception:
            # no sound hardware (e.g. the headless build container):
            # audio becomes a no-op, exactly like the old backend.
            self._failed = True
            return False

    # -- the mixer callback (runs on miniaudio's thread) ------------------
    def _mixer(self) -> Generator[_PCM, int, None]:
        required = yield np.zeros(0, dtype=np.float32)
        while True:
            out = np.zeros(required * _CHANNELS, dtype=np.float32)
            with self._lock:
                voices = list(self._voices)
            for v in voices:
                try:
                    self._mix_voice(v, out, required)
                except Exception:
                    v.done = True
            with self._lock:
                self._voices = [v for v in self._voices if not v.done]
            required = yield out

    def _mix_voice(self, v: _Voice, out: _PCM, frames: int) -> None:
        """Add up to ``frames`` frames of ``v`` into ``out`` (interleaved)."""
        filled = 0
        while filled < frames and not v.done:
            if v.stream is not None:
                chunk = self._next_stream_chunk(v)
                if chunk is None:
                    v.done = True
                    break
                take = min(frames - filled, len(chunk) // _CHANNELS)
                seg = chunk[: take * _CHANNELS]
                # stash any remainder for the next pull
                rest = chunk[take * _CHANNELS :]
                v.samples = rest if len(rest) else None
            else:
                assert v.samples is not None
                total = len(v.samples) // _CHANNELS
                if v.pos >= total:
                    if v.looping:
                        v.pos = 0  # gapless wraparound
                        continue
                    v.done = True
                    break
                take = min(frames - filled, total - v.pos)
                seg = v.samples[v.pos * _CHANNELS : (v.pos + take) * _CHANNELS]
                v.pos += take

            gain: _PCM | float
            if v.fade_step != 0.0:
                # a per-frame linear ramp while fading (in or out)
                ramp = v.fade_gain + v.fade_step * np.arange(
                    1, take + 1, dtype=np.float32
                )
                np.clip(ramp, 0.0, 1.0, out=ramp)
                v.fade_gain = float(ramp[-1])
                if v.fade_step > 0 and v.fade_gain >= 1.0:
                    v.fade_gain, v.fade_step = 1.0, 0.0
                gain = np.repeat(ramp, _CHANNELS) * v.volume
                if v.fade_gain <= 0.0 and v.stop_when_faded:
                    v.done = True
            else:
                gain = v.fade_gain * v.volume
            sl = slice(filled * _CHANNELS, (filled + take) * _CHANNELS)
            out[sl] += seg * gain
            filled += take

    def _next_stream_chunk(self, v: _Voice) -> _PCM | None:
        """The music path: the leftover stash, else the next decoded chunk."""
        if v.samples is not None and len(v.samples):
            chunk, v.samples = v.samples, None
            return chunk
        assert v.stream is not None
        try:
            return np.asarray(next(v.stream), dtype=np.float32)
        except StopIteration:
            return None

    # -- game-thread API ---------------------------------------------------
    def play_buffer(
        self,
        samples: _PCM,
        volume: float,
        looping: bool,
        fade_in_ms: float,
    ) -> _Voice | None:
        if not self._ensure_device():
            return None
        v = _Voice(samples, None, volume, looping, fade_in_ms)
        with self._lock:
            self._voices.append(v)
        return v

    def play_stream(
        self, stream: Iterator[Any], volume: float, fade_in_ms: float = 0.0
    ) -> _Voice | None:
        if not self._ensure_device():
            return None
        v = _Voice(None, stream, volume, looping=False, fade_in_ms=fade_in_ms)
        with self._lock:
            self._voices.append(v)
        return v

    def stop_voice(self, v: _Voice) -> None:
        with self._lock:
            v.done = True


_engine = _Engine()


def _decode(path: str) -> _PCM:
    decoded = _ma.decode_file(
        path,
        output_format=_ma.SampleFormat.FLOAT32,
        nchannels=_CHANNELS,
        sample_rate=_SAMPLE_RATE,
    )
    return np.asarray(decoded.samples, dtype=np.float32)


class Sound:
    """A single sound effect: decoded ONCE into a shared buffer; each play is
    a lightweight mixer voice over that buffer (pygame.mixer semantics)."""

    def __init__(self, path: str) -> None:
        self.path = path
        self._samples: _PCM | None = None
        self._volume: float = 1.0
        self._voices: list[_Voice] = []

    def _buffer(self) -> _PCM | None:
        if self._samples is None:
            try:
                self._samples = _decode(self.path)
            except Exception:
                return None
        return self._samples

    def _live(self) -> list[_Voice]:
        self._voices = [v for v in self._voices if not v.done]
        return self._voices

    def play(
        self,
        loops: int = 0,
        maxtime: int = 0,
        fade_ms: int = 0,
        volume: float | None = None,
    ) -> None:
        """Play the effect (overlapping prior plays); ``loops != 0`` loops it.

        ``maxtime`` is accepted for ``pygame.mixer.Sound.play`` compatibility
        but ignored.  ``fade_ms`` ramps this play's voice up from silence
        inside the mixer.  ``volume`` overrides this effect's volume for THIS
        play only (the mixer.Sound wrapper in ``__init__`` uses this to give
        pygame's per-instance-volume semantics without a Sound per volume).
        """
        if not _BACKEND:
            return
        buf = self._buffer()
        if buf is None:
            return
        live = self._live()
        if len(live) >= _MAX_VOICES_PER_SOUND:
            _engine.stop_voice(live[0])  # oldest voice yields its budget
        v = _engine.play_buffer(
            buf,
            self._volume if volume is None else volume,
            looping=loops != 0,
            fade_in_ms=fade_ms,
        )
        if v is not None:
            self._voices.append(v)

    def stop(self) -> None:
        """Stop all currently-playing instances of this effect."""
        for v in self._live():
            _engine.stop_voice(v)

    def set_volume(self, v: float) -> None:
        """Set this effect's volume (0.0-1.0), applied to current + future plays."""
        self._volume = v
        for voice in self._live():
            voice.volume = v

    def get_volume(self) -> float:
        """Return this effect's current volume (0.0-1.0)."""
        return self._volume

    def fadeout(self, time: int = 0) -> None:
        """Ramp all playing instances to silence over ``time`` ms, then stop
        them (pygame semantics; the ramp runs per-frame inside the mixer).
        ``time <= 0`` stops immediately."""
        if time <= 0:
            self.stop()
            return
        for v in self._live():
            v.start_fadeout(time)


class _Music:
    """The single streamed background track (pgzero's `music` object)."""

    def __init__(self) -> None:
        self._voice: _Voice | None = None
        self._volume: float = 1.0
        self._looping: bool = False

    def _path(self, name: str) -> str | None:
        """Resolve a track ``name`` to a file under ``music/``, or ``None``."""
        base: str = os.path.join(context.get_asset_root(), "music", name)
        if os.path.isfile(base):
            return base
        for ext in ("ogg", "mp3", "wav"):
            p: str = base + "." + ext
            if os.path.exists(p):
                return p
        return None

    def _stream(self, path: str) -> Iterator[Any]:
        outer = self

        def gen() -> Iterator[Any]:
            # music streams from disk (a decoded multi-minute track would be
            # tens of MB); looping restarts the stream -- like SDL_mixer's
            # streamed music, the loop seam lands on a chunk boundary.
            while True:
                inner = _ma.stream_file(
                    path,
                    output_format=_ma.SampleFormat.FLOAT32,
                    nchannels=_CHANNELS,
                    sample_rate=_SAMPLE_RATE,
                    frames_to_read=1024,
                )
                for chunk in inner:
                    yield chunk
                if not outer._looping:
                    return

        return gen()

    def _play(self, name: str, loop: bool) -> None:
        if not _BACKEND:
            return
        p: str | None = self._path(name)
        if not p:
            self.stop()
            return
        try:
            self.stop()
            self._looping = loop
            self._voice = _engine.play_stream(self._stream(p), self._volume)
        except Exception:
            self._voice = None

    def play(self, name: str) -> None:
        """Play track ``name`` on loop."""
        self._play(name, loop=True)

    def play_once(self, name: str) -> None:
        """Play track ``name`` a single time."""
        self._play(name, loop=False)

    def set_volume(self, v: float) -> None:
        """Set the music volume (0.0-1.0), applied to the current track if any."""
        self._volume = v
        if self._voice is not None and not self._voice.done:
            self._voice.volume = v

    def get_volume(self) -> float:
        """Return the music volume (0.0-1.0)."""
        return self._volume

    def stop(self) -> None:
        """Stop the current track."""
        self._looping = False
        if self._voice is not None:
            _engine.stop_voice(self._voice)
            self._voice = None

    def fadeout(self, seconds: float) -> None:
        """Ramp the track to silence over ``seconds``, then stop it."""
        if self._voice is None or self._voice.done or seconds <= 0:
            self.stop()
            return
        self._looping = False
        self._voice.start_fadeout(seconds * 1000.0)


music = _Music()
