# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: src/modelviewprojection/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""Shared, process-wide runtime state for the ``pgzero_gl`` shim.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

A tiny holder for state that several shim modules need but which is only known
once the game starts: the active :class:`~pgzero_gl.renderer.Renderer` (created
after the GL context exists) and the asset root directory. It is a **class**
(``Context``) with class-level state, not module globals -- so both the shim and
the single-file inlined games (each game inlines the whole shim) stay
type-checker-legible: ``Context.renderer = ...`` is a typed class-attribute
assignment ty understands, whereas a module-global reached through a
``sys.modules[__name__]`` alias (which the inlined games would need) is not. It
keeps the same job: one shared holder imported everywhere, so the renderer isn't
threaded through every draw call and there are no import cycles.
"""

from __future__ import annotations

import os
import sys
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .renderer import Renderer


class Context:
    """Process-wide shim state. The class attributes ARE the shared state."""

    #: The active renderer. ``None`` until the runner creates the GL context;
    #: drawing before then raises a clear error (see :meth:`require_renderer`).
    renderer: Renderer | None = None

    #: The active GLFW window handle (set by the runner; used by ``exit()``).
    #: GLFW handles are opaque pointers, so this is typed ``Any``.
    window: Any = None

    #: ``True`` once ``glfw.init()`` has succeeded. Joystick queries must not
    #: touch GLFW before this (games call ``setup_joystick_controls()`` at import
    #: time, before the window/loop exist).
    glfw_ready: bool = False

    #: Directory holding the game's ``images/``/``sounds/``/``music/``. ``None``
    #: means "resolve lazily": game objects (hence asset loads) are routinely
    #: created at import time, before ``main()`` runs, so the root is inferred
    #: from the main script's location when it hasn't been set explicitly.
    asset_root: str | None = None

    @staticmethod
    def get_asset_root() -> str:
        """Return the dir holding ``images/``/``sounds/``/``music/``.

        Uses :attr:`asset_root` if set; otherwise infers it from the main
        script's location (assets load at import time, before ``main()`` could
        set it), falling back to the current working directory.
        """
        if Context.asset_root is not None:
            return Context.asset_root
        main = sys.modules.get("__main__")
        main_file = getattr(main, "__file__", None)
        if main_file:
            return os.path.dirname(os.path.abspath(main_file))
        return os.getcwd()

    @staticmethod
    def require_renderer() -> Renderer:
        """Return the active renderer, or raise if the GL context isn't up yet.

        Raises ``RuntimeError`` if called before the game loop created the GL
        context (i.e. if a game tries to draw at import time).
        """
        if Context.renderer is None:
            raise RuntimeError(
                "No GL renderer yet -- drawing happens inside the game loop "
                "(after main()).  Don't draw at import time."
            )
        return Context.renderer
