# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""A minimal ``pygame.mask`` work-alike.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol2
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

``avenger`` builds a collision mask from its terrain image and queries per-pixel
opacity (:meth:`Mask.get_at`). We back the mask with the image's alpha channel
(kept on the CPU already), so this needs no GL.
"""

from __future__ import annotations

from numpy.typing import NDArray

from ._types import Point, PointLike, RGBASource


class Mask:
    """A boolean per-pixel opacity grid, queried like ``pygame.mask.Mask``."""

    def __init__(self, alpha: NDArray) -> None:
        self._a = alpha  # HxW bool/uint8: True where opaque
        self.height: int = int(alpha.shape[0])
        self.width: int = int(alpha.shape[1])

    def get_size(self) -> tuple[int, int]:
        """Return ``(width, height)`` in pixels."""
        return (self.width, self.height)

    def get_at(self, pos: PointLike) -> int:
        """Return ``1`` if the pixel at ``pos`` is opaque, else ``0`` (or out of bounds)."""
        px, py = pos  # unpack: tuple OR gacalc vector
        x, y = int(px), int(py)
        if 0 <= x < self.width and 0 <= y < self.height:
            return 1 if self._a[y, x] else 0
        return 0

    def overlap(self, other: Mask, offset: PointLike) -> Point | None:
        # Bounding-box-clipped per-pixel AND of the two masks (rare; provided for
        # completeness).  Returns a colliding point or None.
        """Return a point where ``self`` and ``other`` (shifted by ``offset``) both
        have opaque pixels, or ``None`` if they do not overlap."""
        o_x, o_y = offset  # unpack: tuple OR gacalc vector
        ox, oy = int(o_x), int(o_y)
        for y in range(max(0, oy), min(self.height, oy + other.height)):
            for x in range(max(0, ox), min(self.width, ox + other.width)):
                if self._a[y, x] and other._a[y - oy, x - ox]:
                    return (x, y)
        return None


def from_surface(surface: RGBASource, threshold: int = 127) -> Mask:
    """Build a :class:`Mask` from an Image/Surface; pixels with alpha > threshold are opaque."""
    return Mask(surface.rgba[..., 3] > threshold)
