# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

"""A CPU-backed ``pygame.Surface`` work-alike.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol2
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

Some Vol 2 games build an offscreen ``pygame.Surface`` and composite into it
(``kinetix`` accumulates broken-brick sprites; ``beatstreets``/``leadingedge``
use a full-screen black overlay). We back a :class:`Surface` with a CPU RGBA
numpy buffer: :meth:`~Surface.fill` and :meth:`~Surface.blit` composite on the
CPU (these surfaces change rarely -- e.g. only when a brick breaks), and the GL
texture is re-uploaded lazily when the buffer is dirty. A :class:`Surface` is
drawable by :meth:`Screen.blit` because it exposes the same
``width``/``height``/:meth:`~Surface.gl_texture` interface as
:class:`pgzero_gl.resources.Image` (the :class:`pgzero_gl._types.Drawable`
protocol).
"""

from __future__ import annotations

from collections.abc import Sequence
from typing import Any, cast

import numpy as np
import OpenGL.GL as GL
from numpy.typing import NDArray

from . import context
from ._types import Color, ColorRGBA, PointLike, RGBASource
from .geometry import Rect

SRCALPHA = 0x00010000


def _rgba_tuple(color: Sequence[int]) -> ColorRGBA:
    """Normalise an RGB or RGBA colour to a 4-tuple of ints (RGB -> opaque)."""
    if len(color) == 3:
        return (int(color[0]), int(color[1]), int(color[2]), 255)
    return (int(color[0]), int(color[1]), int(color[2]), int(color[3]))


class Surface:
    """An offscreen RGBA image the games can ``fill``/``blit`` into and then draw."""

    def __init__(self, size: PointLike, flags: int = 0) -> None:
        w_f, h_f = size  # unpack: tuple OR gacalc vector
        w, h = int(w_f), int(h_f)
        self.width: int = w
        self.height: int = h
        # SRCALPHA -> start transparent; otherwise opaque black (pygame default).
        self.rgba: NDArray[np.uint8] = np.zeros((h, w, 4), dtype=np.uint8)
        if not (flags & SRCALPHA):
            self.rgba[..., 3] = 255
        self._tex: int | None = None
        self._dirty: bool = True

    # -- pygame.Surface API the games use -------------------------------------
    def fill(self, color: Color, rect: PointLike | None = None) -> None:
        """Fill the whole surface (or the ``rect`` sub-region) with ``color``."""
        r, g, b, a = _rgba_tuple(color)
        if rect is None:
            self.rgba[..., 0] = r
            self.rgba[..., 1] = g
            self.rgba[..., 2] = b
            self.rgba[..., 3] = a
        else:
            x, y, w, h = (int(v) for v in rect)
            x0, y0 = max(0, x), max(0, y)
            x1, y1 = min(self.width, x + w), min(self.height, y + h)
            if x1 > x0 and y1 > y0:
                self.rgba[y0:y1, x0:x1] = (r, g, b, a)
        self._dirty = True

    def blit(
        self, src: RGBASource, pos: PointLike, area: PointLike | None = None
    ) -> None:
        """Alpha-composite ``src`` (optionally a sub-``area`` of it) onto this surface at ``pos``."""
        src_rgba: NDArray[np.uint8] = src.rgba
        if area is not None:
            ax, ay, aw, ah = (int(v) for v in area)
            src_rgba = src_rgba[ay : ay + ah, ax : ax + aw]
        sh, sw = src_rgba.shape[0], src_rgba.shape[1]
        px, py = pos  # unpack: tuple OR gacalc vector
        x, y = int(px), int(py)
        # Clip to destination bounds.
        dx0, dy0 = max(0, x), max(0, y)
        dx1, dy1 = min(self.width, x + sw), min(self.height, y + sh)
        if dx1 <= dx0 or dy1 <= dy0:
            return
        sx0, sy0 = dx0 - x, dy0 - y
        s: NDArray[np.float32] = src_rgba[
            sy0 : sy0 + (dy1 - dy0), sx0 : sx0 + (dx1 - dx0)
        ].astype(np.float32)
        d: NDArray[np.float32] = self.rgba[dy0:dy1, dx0:dx1].astype(np.float32)
        # straight-alpha src-over
        sa: NDArray[np.float32] = s[..., 3:4] / 255.0
        da: NDArray[np.float32] = d[..., 3:4] / 255.0
        out_a: NDArray[np.float32] = sa + da * (1.0 - sa)
        with np.errstate(invalid="ignore", divide="ignore"):
            out_rgb: NDArray[Any] = (
                s[..., :3] * sa + d[..., :3] * da * (1.0 - sa)
            ) / np.where(out_a == 0, 1.0, out_a)
        self.rgba[dy0:dy1, dx0:dx1, :3] = np.clip(out_rgb, 0, 255).astype(
            np.uint8
        )
        self.rgba[dy0:dy1, dx0:dx1, 3:4] = np.clip(
            out_a * 255.0, 0, 255
        ).astype(np.uint8)
        self._dirty = True

    def get_width(self) -> int:
        """Return the surface width in pixels."""
        return self.width

    def get_height(self) -> int:
        """Return the surface height in pixels."""
        return self.height

    def get_size(self) -> tuple[int, int]:
        """Return ``(width, height)`` in pixels."""
        return (self.width, self.height)

    def get_rect(self, **kwargs: Any) -> Rect:
        """Return a :class:`Rect` the size of this surface; ``kwargs`` set anchor attrs."""
        r: Rect = Rect(0, 0, self.width, self.height)
        for k, v in kwargs.items():
            setattr(r, k, v)
        return r

    def set_alpha(self, a: int | float | None) -> None:
        # Uniform surface alpha (used for fades).  Scale the alpha channel.
        """Scale the whole surface's alpha by ``a`` (0-255); ``None`` is a no-op (used for fades)."""
        if a is None:
            return
        self.rgba[..., 3] = np.clip(
            self.rgba[..., 3].astype(np.float32) * (a / 255.0), 0, 255
        ).astype(np.uint8)
        self._dirty = True

    # -- drawable-by-screen.blit interface (like resources.Image) -------------
    def gl_texture(self) -> int:
        """Return this surface's GL texture name, uploading the CPU buffer if dirty."""
        context.require_renderer()
        if self._tex is None:
            self._tex = GL.glGenTextures(1)
        if self._dirty:
            GL.glBindTexture(GL.GL_TEXTURE_2D, self._tex)
            for p in (GL.GL_TEXTURE_MIN_FILTER, GL.GL_TEXTURE_MAG_FILTER):
                GL.glTexParameteri(GL.GL_TEXTURE_2D, p, GL.GL_NEAREST)
            for p in (GL.GL_TEXTURE_WRAP_S, GL.GL_TEXTURE_WRAP_T):
                GL.glTexParameteri(GL.GL_TEXTURE_2D, p, GL.GL_CLAMP_TO_EDGE)
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGBA,
                self.width,
                self.height,
                0,
                GL.GL_RGBA,
                GL.GL_UNSIGNED_BYTE,
                np.ascontiguousarray(self.rgba),
            )
            self._dirty = False
        return cast(int, self._tex)
