# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: src/modelviewprojection/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt
"""
boing_gl1 -- the OpenGL 1.x (fixed-function) rendering of boing.

A study companion to boing.py: the SAME game, drawn with the OpenGL 1.x
fixed-function pipeline (a 2.1 compatibility context + glOrtho + glBegin/glEnd
immediate mode + fixed-function texturing) instead of 3.3 core + shaders. Diff
this file against boing.py to see exactly what changes between the two pipelines
-- the game logic is identical; only the renderer (Renderer1x, below) and the
window/context setup differ. The fixed-function era here is the one the book
introduces at demo19 (glMatrixMode / glOrtho / glBegin / glEnable(GL_TEXTURE_2D)).
"""

from __future__ import annotations

import os
import random
import signal
import sys
import threading
import time
from collections.abc import Callable, Generator, Iterable, Iterator, Sequence
from dataclasses import InitVar, dataclass, field
from enum import Enum
from typing import TYPE_CHECKING, Any, Protocol, cast

import glfw
import numpy as np
import OpenGL.GL as GL
from gacalc.g2 import Vector
from numpy.typing import NDArray
from PIL import Image as PILImage

# The inlined pgzero_gl modules referenced each other by module name;
# every name is now top-level here, so bind those namespaces to this
# module itself (attribute get/set reaches the module globals). A step-1
# mechanical artifact -- step 2 dissolves it when the game owns the loop.
_text = audio = sys.modules[__name__]

# ===== pgzero_gl/_types.py =====

"""Shared type aliases and structural (``Protocol``) types for the shim.

These exist so the per-module annotations stay short and consistent. Nothing
here imports another shim module, so it is import-cycle-safe to pull from
anywhere in ``pgzero_gl``.
"""


# A colour as the games supply it: 3 (RGB) or 4 (RGBA) channels, each 0-255.
ColorRGB = tuple[int, int, int]
ColorRGBA = tuple[int, int, int, int]
Color = ColorRGB | ColorRGBA

# A 2-D position in PyGame Zero's top-left-origin, y-down pixel space. ``Point``
# is the concrete pair the shim returns; ``PointLike`` is what it accepts (the
# games pass tuples, lists, or gacalc vectors -- anything unpack-able as x, y).
Point = tuple[float, float]
PointLike = Sequence[float] | Vector

# An anchor spec: each component is a named fraction ("left"/"center"/...)
# or a literal pixel offset.
Anchor = tuple[str | float, str | float]


class Drawable(Protocol):
    """Anything :meth:`Screen.blit` can draw: an image-like backed by a GL texture.

    Both :class:`pgzero_gl.resources.Image` and
    :class:`pgzero_gl.surface.Surface` satisfy this.
    """

    width: int
    height: int

    def gl_texture(self) -> int: ...


class RGBASource(Protocol):
    """Anything backed by an ``H x W x 4`` ``uint8`` RGBA CPU buffer.

    Used where the shim reads pixels (collision masks, compositing): both
    :class:`pgzero_gl.resources.Image` and :class:`pgzero_gl.surface.Surface`
    expose ``rgba``.
    """

    rgba: NDArray[np.uint8]


# ===== pgzero_gl/context.py =====

"""Shared, process-wide runtime state for the ``pgzero_gl`` shim.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

A tiny holder for state that several shim modules need but which is only known
once the game starts: the active :class:`~pgzero_gl.renderer_gl1.Renderer1x` (created
after the GL context exists) and the asset root directory. It is a **class**
(``Context``) with class-level state, not module globals -- so both the shim and
the single-file inlined games (each game inlines the whole shim) stay
type-checker-legible: ``Context.renderer = ...`` is a typed class-attribute
assignment ty understands, whereas a module-global reached through a
``sys.modules[__name__]`` alias (which the inlined games would need) is not. It
keeps the same job: one shared holder imported everywhere, so the renderer isn't
threaded through every draw call and there are no import cycles.
"""


if TYPE_CHECKING:
    pass


class Context:
    """Process-wide shim state. The class attributes ARE the shared state."""

    #: The active renderer. ``None`` until the runner creates the GL context;
    #: drawing before then raises a clear error (see :meth:`require_renderer`).
    renderer: Renderer1x | None = None

    #: The active GLFW window handle (set by the runner; used by ``exit()``).
    #: GLFW handles are opaque pointers, so this is typed ``Any``.
    window: Any = None

    #: ``True`` once ``glfw.init()`` has succeeded. Joystick queries must not
    #: touch GLFW before this (games call ``setup_joystick_controls()`` at import
    #: time, before the window/loop exist).
    glfw_ready: bool = False

    #: Directory holding the game's ``images/``/``sounds/``/``music/``. ``None``
    #: means "resolve lazily": game objects (hence asset loads) are routinely
    #: created at import time, before ``main()`` runs, so the root is inferred
    #: from the main script's location when it hasn't been set explicitly.
    asset_root: str | None = None

    @staticmethod
    def get_asset_root() -> str:
        """Return the dir holding ``images/``/``sounds/``/``music/``.

        Uses :attr:`asset_root` if set; otherwise infers it from the main
        script's location (assets load at import time, before ``main()`` could
        set it), falling back to the current working directory.
        """
        if Context.asset_root is not None:
            return Context.asset_root
        main = sys.modules.get("__main__")
        main_file = getattr(main, "__file__", None)
        if main_file:
            return os.path.dirname(os.path.abspath(main_file))
        return os.getcwd()

    @staticmethod
    def require_renderer() -> Renderer1x:
        """Return the active renderer, or raise if the GL context isn't up yet.

        Raises ``RuntimeError`` if called before the game loop created the GL
        context (i.e. if a game tries to draw at import time).
        """
        if Context.renderer is None:
            raise RuntimeError(
                "No GL renderer yet -- drawing happens inside the game loop "
                "(after main()).  Don't draw at import time."
            )
        return Context.renderer


# ===== pgzero_gl/audio.py =====

"""Sound + music, without pygame -- PyGame Zero's ``sounds`` and ``music``.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

PyGame Zero gets audio from ``pygame.mixer`` (SDL). We deliberately avoid
pygame here (the project's host runs an SDL2-on-SDL3 shim that breaks SDL
audio) -- but we DO mirror pygame.mixer's architecture, because the games
were written against it: **one** output device opened once, every effect
decoded into an in-memory buffer at load, and N voices software-mixed in
the device's audio callback. Loops are gapless (buffer wraparound in the
mixer), fades are per-frame volume ramps inside the callback, and starting
or stopping a voice is a flag flip -- zero OS device operations after
startup.

History (2026-07-09): the previous backend (just_playback) opened a
SEPARATE miniaudio stream per voice. leadingedge's 41-sample engine
crossfade turned that into dozens of concurrent ALSA/PipeWire streams --
audibly clunky band changes (device start/stop clicks, plus decode on the
game thread per new band) and eventually a frozen game once the audio
client slots ran out and snd_pcm blocked the game thread. Root-cause
analysis: tasks/leadingedge-audio-clunk-and-freeze.md.

Audio remains BEST EFFORT: if miniaudio can't be imported or a device can't
be opened, every call becomes a no-op. The original games already wrap
sound in try/except, so silence never breaks gameplay -- and on-screen GL
is what gets human-verified here anyway (no audio device in the build
container).
"""


if TYPE_CHECKING:
    import miniaudio

#: interleaved float32 PCM at the mixing format
_PCM = NDArray[np.float32]

# the miniaudio module (or None if unavailable); Any so the sentinel and
# the module share a type
_ma: Any = None
_BACKEND: bool = False
try:
    import miniaudio as _miniaudio

    _ma = _miniaudio
    _BACKEND = True
except Exception:  # pragma: no cover - depends on runtime env
    pass


def available() -> bool:
    """Return whether an audio backend loaded (False -> all audio is a no-op)."""
    return _BACKEND


# One mixing format for everything; decode/stream converts to it.
_SAMPLE_RATE = 44100
_CHANNELS = 2

# pygame.mixer defaults to 8 mixing channels; cap concurrent voices per
# effect similarly so a rapidly-refired sound reuses its budget.
_MAX_VOICES_PER_SOUND = 8


@dataclass(slots=True)
class _Voice:
    """One playing instance inside the mixer: a position in a shared buffer
    (effects) or a pull-stream (music), plus volume/loop/fade state.

    Mutated under the engine lock; consumed by the mixer callback.
    """

    samples: _PCM | None
    stream: Iterator[Any] | None
    volume: float
    looping: bool
    #: fade-in duration; consumed by __post_init__ into the ramp fields
    fade_in_ms: InitVar[float]
    #: frame offset into ``samples`` (buffer voices only)
    pos: int = field(default=0, init=False)
    #: fade_gain multiplies volume and ramps by fade_step per FRAME
    fade_gain: float = field(default=1.0, init=False)
    fade_step: float = field(default=0.0, init=False)
    stop_when_faded: bool = field(default=False, init=False)
    done: bool = field(default=False, init=False)

    def __post_init__(self, fade_in_ms: float) -> None:
        if fade_in_ms > 0:
            self.fade_gain = 0.0
            self.fade_step = 1.0 / (_SAMPLE_RATE * fade_in_ms / 1000.0)

    def start_fadeout(self, ms: float) -> None:
        frames = max(_SAMPLE_RATE * ms / 1000.0, 1.0)
        self.fade_step = -self.fade_gain / frames
        self.stop_when_faded = True


class _Engine:
    """The single miniaudio PlaybackDevice + the software mixer feeding it."""

    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._voices: list[_Voice] = []
        self._device: miniaudio.PlaybackDevice | None = None
        self._failed = False

    # -- device ---------------------------------------------------------
    def _ensure_device(self) -> bool:
        if self._device is not None:
            return True
        if self._failed or not _BACKEND:
            return False
        try:
            device = _ma.PlaybackDevice(
                output_format=_ma.SampleFormat.FLOAT32,
                nchannels=_CHANNELS,
                sample_rate=_SAMPLE_RATE,
            )
            gen = self._mixer()
            next(gen)  # prime the generator protocol
            # numpy arrays satisfy the buffer protocol miniaudio consumes;
            # its stubs only admit bytes/array.array, hence the cast.
            device.start(cast(Any, gen))
            self._device = device
            return True
        except Exception:
            # no sound hardware (e.g. the headless build container):
            # audio becomes a no-op, exactly like the old backend.
            self._failed = True
            return False

    # -- the mixer callback (runs on miniaudio's thread) ------------------
    def _mixer(self) -> Generator[_PCM, int, None]:
        required = yield np.zeros(0, dtype=np.float32)
        while True:
            out = np.zeros(required * _CHANNELS, dtype=np.float32)
            with self._lock:
                voices = list(self._voices)
            for v in voices:
                try:
                    self._mix_voice(v, out, required)
                except Exception:
                    v.done = True
            with self._lock:
                self._voices = [v for v in self._voices if not v.done]
            required = yield out

    def _mix_voice(self, v: _Voice, out: _PCM, frames: int) -> None:
        """Add up to ``frames`` frames of ``v`` into ``out`` (interleaved)."""
        filled = 0
        while filled < frames and not v.done:
            if v.stream is not None:
                chunk = self._next_stream_chunk(v)
                if chunk is None:
                    v.done = True
                    break
                take = min(frames - filled, len(chunk) // _CHANNELS)
                seg = chunk[: take * _CHANNELS]
                # stash any remainder for the next pull
                rest = chunk[take * _CHANNELS :]
                v.samples = rest if len(rest) else None
            else:
                assert v.samples is not None
                total = len(v.samples) // _CHANNELS
                if v.pos >= total:
                    if v.looping:
                        v.pos = 0  # gapless wraparound
                        continue
                    v.done = True
                    break
                take = min(frames - filled, total - v.pos)
                seg = v.samples[v.pos * _CHANNELS : (v.pos + take) * _CHANNELS]
                v.pos += take

            gain: _PCM | float
            if v.fade_step != 0.0:
                # a per-frame linear ramp while fading (in or out)
                ramp = v.fade_gain + v.fade_step * np.arange(
                    1, take + 1, dtype=np.float32
                )
                np.clip(ramp, 0.0, 1.0, out=ramp)
                v.fade_gain = float(ramp[-1])
                if v.fade_step > 0 and v.fade_gain >= 1.0:
                    v.fade_gain, v.fade_step = 1.0, 0.0
                gain = np.repeat(ramp, _CHANNELS) * v.volume
                if v.fade_gain <= 0.0 and v.stop_when_faded:
                    v.done = True
            else:
                gain = v.fade_gain * v.volume
            sl = slice(filled * _CHANNELS, (filled + take) * _CHANNELS)
            out[sl] += seg * gain
            filled += take

    def _next_stream_chunk(self, v: _Voice) -> _PCM | None:
        """The music path: the leftover stash, else the next decoded chunk."""
        if v.samples is not None and len(v.samples):
            chunk, v.samples = v.samples, None
            return chunk
        assert v.stream is not None
        try:
            return np.asarray(next(v.stream), dtype=np.float32)
        except StopIteration:
            return None

    # -- game-thread API ---------------------------------------------------
    def play_buffer(
        self,
        samples: _PCM,
        volume: float,
        looping: bool,
        fade_in_ms: float,
    ) -> _Voice | None:
        if not self._ensure_device():
            return None
        v = _Voice(samples, None, volume, looping, fade_in_ms)
        with self._lock:
            self._voices.append(v)
        return v

    def play_stream(
        self, stream: Iterator[Any], volume: float, fade_in_ms: float = 0.0
    ) -> _Voice | None:
        if not self._ensure_device():
            return None
        v = _Voice(None, stream, volume, looping=False, fade_in_ms=fade_in_ms)
        with self._lock:
            self._voices.append(v)
        return v

    def stop_voice(self, v: _Voice) -> None:
        with self._lock:
            v.done = True

    def shutdown(self) -> None:
        """Stop the output device and its native callback thread.

        miniaudio's ``PlaybackDevice`` runs its mixer callback on a background
        thread that is NOT a Python ``threading.Thread``; if it is left running
        when the game loop ends, the process hangs on exit -- the window closes
        but Python never returns (seen on real hardware playing music; headless
        the device never opens, so this is a no-op there). Closing the device
        stops that thread. Idempotent and best-effort -- audio is optional.

        The device is closed with the lock RELEASED: ``close()`` joins the
        callback thread, which itself takes ``self._lock`` in the mixer, so
        holding it here would deadlock.
        """
        with self._lock:
            self._voices = []
            device = self._device
            self._device = None
        if device is not None:
            try:
                device.close()
            except Exception:
                pass


_engine = _Engine()


def shutdown() -> None:
    """Tear down the audio backend at game exit (see :meth:`_Engine.shutdown`)."""
    _engine.shutdown()


def _decode(path: str) -> _PCM:
    decoded = _ma.decode_file(
        path,
        output_format=_ma.SampleFormat.FLOAT32,
        nchannels=_CHANNELS,
        sample_rate=_SAMPLE_RATE,
    )
    return np.asarray(decoded.samples, dtype=np.float32)


class Sound:
    """A single sound effect: decoded ONCE into a shared buffer; each play is
    a lightweight mixer voice over that buffer (pygame.mixer semantics)."""

    def __init__(self, path: str) -> None:
        self.path = path
        self._samples: _PCM | None = None
        self._volume: float = 1.0
        self._voices: list[_Voice] = []

    def _buffer(self) -> _PCM | None:
        if self._samples is None:
            try:
                self._samples = _decode(self.path)
            except Exception:
                return None
        return self._samples

    def _live(self) -> list[_Voice]:
        self._voices = [v for v in self._voices if not v.done]
        return self._voices

    def play(
        self,
        loops: int = 0,
        fade_ms: int = 0,
        volume: float | None = None,
    ) -> None:
        """Play the effect (overlapping prior plays); ``loops != 0`` loops it.

        ``fade_ms`` ramps this play's voice up from silence inside the mixer.
        ``volume`` overrides this effect's volume for THIS play only (the
        mixer.Sound wrapper in ``__init__`` uses this to give pygame's
        per-instance-volume semantics without a Sound per volume).
        """
        if not _BACKEND:
            return
        buf = self._buffer()
        if buf is None:
            return
        live = self._live()
        if len(live) >= _MAX_VOICES_PER_SOUND:
            _engine.stop_voice(live[0])  # oldest voice yields its budget
        v = _engine.play_buffer(
            buf,
            self._volume if volume is None else volume,
            looping=loops != 0,
            fade_in_ms=fade_ms,
        )
        if v is not None:
            self._voices.append(v)

    def stop(self) -> None:
        """Stop all currently-playing instances of this effect."""
        for v in self._live():
            _engine.stop_voice(v)

    def set_volume(self, v: float) -> None:
        """Set this effect's volume (0.0-1.0), applied to current + future plays."""
        self._volume = v
        for voice in self._live():
            voice.volume = v

    def get_volume(self) -> float:
        """Return this effect's current volume (0.0-1.0)."""
        return self._volume

    def fadeout(self, time: int = 0) -> None:
        """Ramp all playing instances to silence over ``time`` ms, then stop
        them (pygame semantics; the ramp runs per-frame inside the mixer).
        ``time <= 0`` stops immediately."""
        if time <= 0:
            self.stop()
            return
        for v in self._live():
            v.start_fadeout(time)


class _Music:
    """The single streamed background track (pgzero's `music` object)."""

    def __init__(self) -> None:
        self._voice: _Voice | None = None
        self._volume: float = 1.0
        self._looping: bool = False

    def _path(self, name: str) -> str | None:
        """Resolve a track ``name`` to a file under ``music/``, or ``None``."""
        base: str = os.path.join(Context.get_asset_root(), "music", name)
        if os.path.isfile(base):
            return base
        for ext in ("ogg", "mp3", "wav"):
            p: str = base + "." + ext
            if os.path.exists(p):
                return p
        return None

    def _stream(self, path: str) -> Iterator[Any]:
        outer = self

        def gen() -> Iterator[Any]:
            # music streams from disk (a decoded multi-minute track would be
            # tens of MB); looping restarts the stream -- like SDL_mixer's
            # streamed music, the loop seam lands on a chunk boundary.
            while True:
                inner = _ma.stream_file(
                    path,
                    output_format=_ma.SampleFormat.FLOAT32,
                    nchannels=_CHANNELS,
                    sample_rate=_SAMPLE_RATE,
                    frames_to_read=1024,
                )
                for chunk in inner:
                    yield chunk
                if not outer._looping:
                    return

        return gen()

    def _play(self, name: str, loop: bool) -> None:
        if not _BACKEND:
            return
        p: str | None = self._path(name)
        if not p:
            self.stop()
            return
        try:
            self.stop()
            self._looping = loop
            self._voice = _engine.play_stream(self._stream(p), self._volume)
        except Exception:
            self._voice = None

    def play(self, name: str) -> None:
        """Play track ``name`` on loop."""
        self._play(name, loop=True)

    def play_once(self, name: str) -> None:
        """Play track ``name`` a single time."""
        self._play(name, loop=False)

    def set_volume(self, v: float) -> None:
        """Set the music volume (0.0-1.0), applied to the current track if any."""
        self._volume = v
        if self._voice is not None and not self._voice.done:
            self._voice.volume = v

    def get_volume(self) -> float:
        """Return the music volume (0.0-1.0)."""
        return self._volume

    def stop(self) -> None:
        """Stop the current track."""
        self._looping = False
        if self._voice is not None:
            _engine.stop_voice(self._voice)
            self._voice = None

    def fadeout(self, seconds: float) -> None:
        """Ramp the track to silence over ``seconds``, then stop it."""
        if self._voice is None or self._voice.done or seconds <= 0:
            self.stop()
            return
        self._looping = False
        self._voice.start_fadeout(seconds * 1000.0)


music = _Music()

# ===== pgzero_gl/resources.py =====

"""Image/sound resource loaders -- PyGame Zero's ``images`` and ``sounds``.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

In pgzero you write ``Actor("ship")`` or ``sounds.explosion.play()`` and it
loads ``images/ship.png`` / ``sounds/explosion.ogg`` lazily, by attribute
access, cached. We reproduce that with :class:`_Loader` and the module-level
:data:`images` / :data:`sounds`.

Key difference from pgzero: images decode to a CPU RGBA array immediately (so
``width``/``height`` and pixel masks are available even before the window
exists), but the GL texture is uploaded lazily on first draw -- because game
objects are routinely constructed at import time, before the GL context exists.
"""


class Image:
    """A loaded image: CPU pixels now, GL texture on first draw."""

    def __init__(self, path: str) -> None:
        self.path: str | None = path
        # Decode with Pillow + convert("RGBA").  This correctly turns palette
        # (mode "P") transparency and grayscale/LA into a real alpha channel --
        # imageio drops palette transparency (returns 3-channel RGB), which made
        # transparent sprite backgrounds render as opaque white boxes.
        arr: NDArray[Any] = np.array(PILImage.open(path).convert("RGBA"))
        self.rgba: NDArray[np.uint8] = np.ascontiguousarray(
            arr.astype(np.uint8)
        )
        self.height: int = int(self.rgba.shape[0])
        self.width: int = int(self.rgba.shape[1])
        self._tex: int | None = None

    @classmethod
    def from_rgba(cls, arr: NDArray) -> Image:
        """Build an Image directly from an HxWx4 uint8 array (used by text.py)."""
        obj: Image = cls.__new__(cls)
        obj.path = None
        obj.rgba = np.ascontiguousarray(arr.astype(np.uint8))
        obj.height, obj.width = int(obj.rgba.shape[0]), int(obj.rgba.shape[1])
        obj._tex = None
        return obj

    # pgzero/pygame Surface-compatible accessors used by some games.
    def get_width(self) -> int:
        """Return the image width in pixels."""
        return self.width

    def get_height(self) -> int:
        """Return the image height in pixels."""
        return self.height

    def gl_texture(self) -> int:
        """Return this image's GL texture name, uploading it to the GPU on first call."""
        if self._tex is None:
            Context.require_renderer()
            self._tex = GL.glGenTextures(1)
            GL.glBindTexture(GL.GL_TEXTURE_2D, self._tex)
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MIN_FILTER, GL.GL_NEAREST
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_MAG_FILTER, GL.GL_NEAREST
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_WRAP_S, GL.GL_CLAMP_TO_EDGE
            )
            GL.glTexParameteri(
                GL.GL_TEXTURE_2D, GL.GL_TEXTURE_WRAP_T, GL.GL_CLAMP_TO_EDGE
            )
            GL.glTexImage2D(
                GL.GL_TEXTURE_2D,
                0,
                GL.GL_RGBA,
                self.width,
                self.height,
                0,
                GL.GL_RGBA,
                GL.GL_UNSIGNED_BYTE,
                self.rgba,
            )
        return cast(int, self._tex)


class _Loader:
    """Attribute/`getattr` access to a resource folder, à la pgzero.

    `images.foo` and `getattr(images, "foo")` both load <root>/<subdir>/foo.<ext>.
    Results are cached.  The `name + str(n)` pattern (e.g. getattr(sounds, "hit0"))
    works because it's just attribute access with a computed name.
    """

    def __init__(
        self, subdir: str, extns: list[str], make: Callable[[str], Any]
    ) -> None:
        self._subdir = subdir
        self._extns = extns
        self._make = make
        self._cache: dict[str, Any] = {}

    def _path(self, name: str) -> str | None:
        """Resolve ``name`` to an on-disk path under the resource folder, or ``None``."""
        base: str = os.path.join(Context.get_asset_root(), self._subdir, name)
        if os.path.isfile(base):
            return base
        for ext in self._extns:
            p: str = base + "." + ext
            if os.path.exists(p):
                return p
        return None

    def load(self, name: str) -> Any:
        """Load (and cache) the resource named ``name``; raise ``KeyError`` if absent."""
        if name in self._cache:
            return self._cache[name]
        p: str | None = self._path(name)
        if p is None:
            raise KeyError(
                "No %s found like %r in %s/"
                % (self._subdir[:-1], name, self._subdir)
            )
        res = self._cache[name] = self._make(p)
        return res

    def __getattr__(self, name: str) -> Any:
        if name.startswith("_"):
            raise AttributeError(name)
        try:
            res = self.load(name)
        except KeyError as e:
            raise AttributeError(*e.args) from None
        # First-touch caching: bind the loaded resource as a real instance
        # attribute so repeat accesses (``images.font048`` every frame in
        # leadingedge -- 148k __getattr__ trips in the audit) resolve
        # statically and never come back through here.
        setattr(self, name, res)
        return res

    # A couple of games iterate the loaded sounds.
    def values(self) -> Iterable[Any]:
        """Return the currently-cached (already-loaded) resources."""
        return self._cache.values()

    def clear(self) -> None:
        """Drop all cached resources."""
        self._cache.clear()


images = _Loader(
    subdir="images", extns=["png", "gif", "jpg", "jpeg", "bmp"], make=Image
)
sounds = _Loader(subdir="sounds", extns=["ogg", "wav", "oga"], make=audio.Sound)

# ===== pgzero_gl/renderer_gl1.py (fixed-function OpenGL 1.x) =====

"""The OpenGL 1.x fixed-function back end -- textured quads in pgzero pixel space.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

PyGame Zero draws by blitting CPU surfaces in a top-left-origin, y-down pixel
coordinate system. We reproduce that exactly with a fixed-function orthographic
projection (``glOrtho``) and immediate-mode textured quads (``glBegin``/``glEnd``
+ ``glTexCoord2f``/``glVertex2f``), so the ported game code keeps its original
pixel coordinates unchanged. Tinting uses the fixed-function texture environment
(``GL_MODULATE``: texture * glColor). This is the GL 1.x rendering of boing;
boing.py is the 3.3-core + shaders sibling that draws the same pixels.
"""


if TYPE_CHECKING:
    pass

# ---------------------------------------------------------------------------
# Fixed-function OpenGL 1.x renderer -- a drop-in for the 3.3-core Renderer.
#
# Draws with the OpenGL 1.x FIXED-FUNCTION pipeline: glOrtho for the pixel-space
# projection, glBegin/glEnd immediate mode + glTexCoord2f/glVertex2f for the
# textured quad, and GL_MODULATE (texture * glColor) for tinting -- no shaders,
# no VAO. The interface is identical to the 3.3 Renderer, so blit()/draw_sprite()
# and all the game code below are unchanged. The texture upload
# (Image.gl_texture, above) is glGenTextures/glTexImage2D, which is
# 1.x-compatible. The 3.3 renderer (boing.py) and this one draw the same pixels.
# ---------------------------------------------------------------------------


class Renderer1x:
    """Fixed-function (OpenGL 1.x) renderer with the same interface as :class:`Renderer`."""

    def __init__(self, width: int, height: int) -> None:
        self.width = width
        self.height = height
        self.fb_width = width
        self.fb_height = height
        GL.glEnable(GL.GL_BLEND)
        GL.glBlendFunc(GL.GL_SRC_ALPHA, GL.GL_ONE_MINUS_SRC_ALPHA)
        GL.glDisable(GL.GL_DEPTH_TEST)
        # Fixed-function texture env: texture * glColor (matches the 3.3 path's
        # frag = texture * uTint).
        GL.glTexEnvi(GL.GL_TEXTURE_ENV, GL.GL_TEXTURE_ENV_MODE, GL.GL_MODULATE)

    # -- frame ----------------------------------------------------------------
    def begin_frame(
        self, fb_width: int | None = None, fb_height: int | None = None
    ) -> None:
        """Start a frame: update framebuffer size, clear, set the pixel-space ortho."""
        if fb_width and fb_height:
            self.fb_width = fb_width
            self.fb_height = fb_height
        GL.glDisable(GL.GL_SCISSOR_TEST)
        GL.glViewport(0, 0, self.fb_width, self.fb_height)
        GL.glClearColor(0.0, 0.0, 0.0, 1.0)
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)
        # Pixel-space projection: (0,0) top-left .. (W,H) bottom-right.
        GL.glMatrixMode(GL.GL_PROJECTION)
        GL.glLoadIdentity()
        GL.glOrtho(0.0, self.width, self.height, 0.0, -1.0, 1.0)
        GL.glMatrixMode(GL.GL_MODELVIEW)
        GL.glLoadIdentity()

    # -- sprites --------------------------------------------------------------
    def draw_image(
        self,
        image: Drawable,
        topleft: PointLike,
        src: Any = None,
    ) -> None:
        """Draw a textured quad (see :meth:`Renderer.draw_image` for the semantics)."""
        tx, ty = topleft
        if src is not None:
            sx, sy, sw, sh = src
            w, h = sw, sh
            u0, v0 = sx / image.width, sy / image.height
            u1, v1 = (sx + sw) / image.width, (sy + sh) / image.height
        else:
            w, h = image.width, image.height
            u0, v0, u1, v1 = 0.0, 0.0, 1.0, 1.0

        GL.glEnable(GL.GL_TEXTURE_2D)
        GL.glBindTexture(GL.GL_TEXTURE_2D, image.gl_texture())
        # Sprites draw untinted; GL_MODULATE multiplies the texture by glColor,
        # which flat fills set to a colour -- so reset it to white.
        GL.glColor4f(1.0, 1.0, 1.0, 1.0)

        GL.glPushMatrix()
        GL.glTranslatef(tx, ty, 0.0)
        GL.glScalef(w, h, 1.0)
        GL.glBegin(GL.GL_QUADS)
        GL.glTexCoord2f(u0, v0)
        GL.glVertex2f(0.0, 0.0)
        GL.glTexCoord2f(u1, v0)
        GL.glVertex2f(1.0, 0.0)
        GL.glTexCoord2f(u1, v1)
        GL.glVertex2f(1.0, 1.0)
        GL.glTexCoord2f(u0, v1)
        GL.glVertex2f(0.0, 1.0)
        GL.glEnd()
        GL.glPopMatrix()

    # -- flat colour ----------------------------------------------------------
    def fill(self, color: Any) -> None:
        """Clear the whole framebuffer to ``color``."""
        c: tuple[float, float, float, float] = _rgba(color)
        GL.glClearColor(c[0], c[1], c[2], c[3])
        GL.glClear(GL.GL_COLOR_BUFFER_BIT)

    def _flat(self, verts: Any, color: Any, mode: Any) -> None:
        """Draw flat-colour ``verts`` (iterable of (x, y)) with GL ``mode``."""
        GL.glDisable(GL.GL_TEXTURE_2D)
        GL.glColor4f(*_rgba(color))
        GL.glBegin(mode)
        for x, y in verts:
            GL.glVertex2f(float(x), float(y))
        GL.glEnd()

    def filled_rect(
        self, x: float, y: float, w: float, h: float, color: Any
    ) -> None:
        """Draw a filled rectangle at ``(x, y)`` of size ``(w, h)``."""
        self._flat(
            verts=[(x, y), (x + w, y), (x + w, y + h), (x, y + h)],
            color=color,
            mode=GL.GL_QUADS,
        )

    def rect(self, x: float, y: float, w: float, h: float, color: Any) -> None:
        """Draw the outline of a rectangle at ``(x, y)`` of size ``(w, h)``."""
        self._flat(
            verts=[(x, y), (x + w, y), (x + w, y + h), (x, y + h)],
            color=color,
            mode=GL.GL_LINE_LOOP,
        )

    def line(self, start: PointLike, end: PointLike, color: Any) -> None:
        """Draw a line segment from ``start`` to ``end``."""
        self._flat(verts=[start, end], color=color, mode=GL.GL_LINES)

    def polygon(self, points: Any, color: Any, filled: bool) -> None:
        """Draw a polygon through ``points`` (filled, or outline)."""
        mode = GL.GL_POLYGON if filled else GL.GL_LINE_LOOP
        # unpack, not index: points may be tuples OR gacalc vectors
        self._flat(
            verts=[(px, py) for px, py in points], color=color, mode=mode
        )

    def circle(
        self, pos: PointLike, radius: float, color: Any, filled: bool
    ) -> None:
        """Draw a circle centred at ``pos`` (filled fan, or outline)."""
        cx, cy = pos
        n: int = 48
        pts = []
        if filled:
            pts.append((cx, cy))
        for i in range(n + 1):
            a: float = 2.0 * np.pi * i / n
            pts.append((cx + radius * np.cos(a), cy + radius * np.sin(a)))
        self._flat(
            verts=pts,
            color=color,
            mode=GL.GL_TRIANGLE_FAN if filled else GL.GL_LINE_STRIP,
        )

    # -- scissor (screen.surface.set_clip) ------------------------------------
    def set_clip(self, rect: Any) -> None:
        """Clip drawing to pixel ``rect`` (``None`` disables clipping)."""
        if rect is None:
            GL.glDisable(GL.GL_SCISSOR_TEST)
            return
        x, y, w, h = rect
        sx = self.fb_width / self.width
        sy = self.fb_height / self.height
        GL.glEnable(GL.GL_SCISSOR_TEST)
        GL.glScissor(
            int(x * sx),
            int(self.fb_height - (y + h) * sy),
            int(w * sx),
            int(h * sy),
        )


def _rgba(color: Any) -> tuple[float, float, float, float]:
    """Normalise a colour to a 0..1 float RGBA 4-tuple.

    Accepts ``(r, g, b)`` or ``(r, g, b, a)`` as 0..255 ints or 0..1 floats.
    """
    if len(color) == 3:
        r, g, b = color
        a: int = 255
    else:
        r, g, b, a = color
    if isinstance(r, float) and r <= 1.0 and isinstance(g, float):
        return (r, g, b, a if a <= 1.0 else a / 255.0)
    return (r / 255.0, g / 255.0, b / 255.0, a / 255.0)


# ===== sprite drawing =====
# boing draws sprites by name. No screen/Actor manager: two module functions
# look up a sprite's texture and draw its quad. (The renderer still owns the GL;
# see the "raw OpenGL" notes in tasks/pgzero-gl-step2-strip-and-restructure.md.)


def blit(name: str, x: float, y: float) -> None:
    """Draw sprite ``name`` with its TOP-LEFT at ``(x, y)`` -- backgrounds and UI."""
    Context.require_renderer().draw_image(
        image=images.load(name), topleft=(x, y)
    )


def draw_sprite(name: str, cx: float, cy: float) -> None:
    """Draw sprite ``name`` CENTRED on ``(cx, cy)`` -- the ball, bats, impacts."""
    img = images.load(name)
    Context.require_renderer().draw_image(
        image=img, topleft=(cx - img.width / 2, cy - img.height / 2)
    )


# ===== pgzero_gl/input.py =====

"""Keyboard input, backed by GLFW -- PyGame Zero's ``keyboard`` and ``keys``.

Part of the ModelViewProjection "Code the Classics" port (originals (c)
Raspberry Pi Press and authors).

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

Reproduces pgzero's ``keyboard`` object (boolean attribute access:
``keyboard.space``, ``keyboard.left``, ...) and the ``keys`` code constants the
games compare against. Both are keyed on GLFW key codes; the runner feeds key
events in via :meth:`Keyboard._press`/:meth:`Keyboard._release`.
"""


# pgzero attribute name -> GLFW key code.
_NAME_TO_KEY: dict[str, int] = {}


def _register() -> None:
    """Populate :data:`_NAME_TO_KEY` with the pgzero key names the games use."""
    # letters a-z, digits 0-9
    for ch in "abcdefghijklmnopqrstuvwxyz":
        _NAME_TO_KEY[ch] = getattr(glfw, "KEY_" + ch.upper())
    for d in "0123456789":
        _NAME_TO_KEY["k_" + d] = getattr(glfw, "KEY_" + d)
        _NAME_TO_KEY[d] = getattr(glfw, "KEY_" + d)
    _NAME_TO_KEY.update(
        {
            "space": glfw.KEY_SPACE,
            "up": glfw.KEY_UP,
            "down": glfw.KEY_DOWN,
            "left": glfw.KEY_LEFT,
            "right": glfw.KEY_RIGHT,
            "return": glfw.KEY_ENTER,
            "enter": glfw.KEY_ENTER,
            "escape": glfw.KEY_ESCAPE,
            "tab": glfw.KEY_TAB,
            "backspace": glfw.KEY_BACKSPACE,
            "lshift": glfw.KEY_LEFT_SHIFT,
            "rshift": glfw.KEY_RIGHT_SHIFT,
            "lctrl": glfw.KEY_LEFT_CONTROL,
            "rctrl": glfw.KEY_RIGHT_CONTROL,
            "lalt": glfw.KEY_LEFT_ALT,
            "ralt": glfw.KEY_RIGHT_ALT,
        }
    )


_register()


class Keyboard:
    """`keyboard.<name>` is True while that key is held."""

    def __init__(self) -> None:
        self._pressed: set[int] = set()

    def _press(self, key: int) -> None:
        """Mark ``key`` (a GLFW code) as held; called by the runner on key-down."""
        self._pressed.add(key)

    def _release(self, key: int) -> None:
        """Mark ``key`` (a GLFW code) as released; called by the runner on key-up."""
        self._pressed.discard(key)

    def __getattr__(self, name: str) -> bool:
        """Return whether the named key (``keyboard.space``, ...) is currently held."""
        if name.startswith("_"):
            raise AttributeError(name)
        code: int | None = _NAME_TO_KEY.get(name.lower())
        if code is None:
            return False
        return code in self._pressed

    def __getitem__(self, code: int) -> bool:
        """Return whether the GLFW key ``code`` is currently held."""
        return code in self._pressed


class _Keys:
    """pgzero `keys.SPACE` etc.  Values are GLFW codes, matching the codes the
    runner records via `Keyboard._press`/`_release`."""

    def __getattr__(self, name: str) -> int:
        if name.startswith("_"):
            raise AttributeError(name)
        code: int | None = _NAME_TO_KEY.get(name.lower())
        if code is None:
            raise AttributeError("Unknown key constant: %s" % name)
        return code


keyboard = Keyboard()
keys = _Keys()

# ===== pgzero_gl/__init__.py =====

"""``pgzero_gl`` -- a PyGame Zero compatibility shim on GLFW + OpenGL 3.3 core.

Part of the ModelViewProjection port of "Code the Classics" from PyGame Zero to
modern OpenGL. The original games are (c) Raspberry Pi Press and their authors
(Andrew Gillett et al.; graphics by Dan Malone; audio by Allister Brimble). This
shim is the rendering/input/audio layer that lets the original game logic run
unmodified on OpenGL.

* Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
* Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed

A ported game replaces its first line ::

    import pgzero, pgzrun, pygame

with ::

    from pgzero_gl import *

and otherwise keeps PyGame Zero's globals: :class:`Actor`, :data:`screen`,
:data:`keyboard`, :data:`keys`, :data:`sounds`, :data:`music`, :data:`images`,
:class:`Rect`, :data:`mixer` (a no-op stand-in for pygame.mixer) and
:func:`main` (this port's launch entry, replacing PyGame Zero's ``pgzrun.go``).
Deeper pygame APIs are real
submodules imported explicitly: :mod:`pgzero_gl.geometry` (Rect/ZRect;
vectors come from gacalc directly),
:mod:`pgzero_gl.draw`, :mod:`pgzero_gl.transform`, :mod:`pgzero_gl.surface`,
:mod:`pgzero_gl.joystick`, :mod:`pgzero_gl.mask`.  (Until 2026-07-08 the shim
instead forged synthetic ``pygame``/``pgzero``/``pgzrun`` modules into
``sys.modules`` so upstream import lines could stay verbatim; that was retired
with the byte-faithfulness rule -- imports now say what they mean.)
"""


# --- the mixer stand-in -----------------------------------------------------
# boing's audio boilerplate calls a small no-op slice of pygame.mixer's API
# (real audio is the inlined audio backend). boing never builds mixer.Sound,
# so the _MixerSound pooling wrapper the vol2 games need is dropped here.
class _Mixer:
    """A no-op stand-in for the ``pygame.mixer`` calls boing makes."""

    def quit(self) -> None:
        pass

    def init(self, *a: Any, **k: Any) -> None:
        pass

    def set_num_channels(self, *a: Any, **k: Any) -> None:
        pass


mixer = _Mixer()


# ===== game code =====

WIDTH: int = 800
HEIGHT: int = 480
TITLE: str = "Boing!"

HALF_WIDTH: int = WIDTH // 2
HALF_HEIGHT: int = HEIGHT // 2

PLAYER_SPEED: int = 6
MAX_AI_SPEED: int = 6


def sign(x: float) -> int:
    # Returns -1 or 1 depending on whether number is positive or negative
    return -1 if x < 0 else 1


# Class for an animation which is displayed briefly whenever the ball bounces
# (eq=False on these dataclasses keeps identity comparison/hashing --
# the generated __eq__ would compare fields and set __hash__ to None)
@dataclass(eq=False)
class Impact:
    x: float
    y: float
    time: int = 0
    image: str = "blank"

    def update(self) -> None:
        # There are 5 impact sprites numbered 0 to 4. We update to a new sprite every 2 frames.
        self.image = "impact" + str(self.time // 2)

        # The Game class maintains a list of Impact instances. In Game.update, if the timer for an object
        # has gone beyond 10, the object is removed from the list.
        self.time += 1


@dataclass(eq=False)
class Ball:
    # dir describes the direction in which the ball is moving, as a unit
    # vector. For example, if dir is (1, 0), the ball is moving to the right,
    # with no movement up or down; if both components are negative, the ball
    # is moving left and up, with the angle depending on their relative
    # values. (The book's original uses two floats, dx and dy, and explains
    # them as a vector; here it IS one -- a gacalc grade-1 vector of the
    # plane's geometric algebra.)
    dir: Vector
    # x/y are the ball's CENTRE, starting in the middle of the screen.
    x: float = HALF_WIDTH
    y: float = HALF_HEIGHT
    speed: int = 5
    image: str = "ball"

    def update(self) -> None:
        # Each frame, we move the ball in a series of small steps - the number of steps being based on its speed attribute
        for _i in range(self.speed):
            # Store the previous x position
            original_x: float = self.x

            # Move the ball based on its direction vector
            self.x += self.dir.x
            self.y += self.dir.y

            # Check to see if ball needs to bounce off a bat

            # To determine whether the ball might collide with a bat, we first measure the horizontal distance from the
            # ball to the centre of the screen, and check to see if its edge has gone beyond the edge of the bat.
            # The centre of each bat is 40 pixels from the edge of the screen, or to put it another way, 360 pixels
            # from the centre of the screen. The bat is 18 pixels wide and the ball is 14 pixels wide. Given that these
            # sprites are anchored from their centres, when determining if they overlap or touch, we need to look at
            # their half-widths - 9 and 7. Therefore, if the centre of the ball is 344 pixels from the centre of the
            # screen, it can bounce off a bat (assuming the bat is in the right position on the Y axis - checked
            # shortly afterwards).
            # We also check the previous X position to ensure that this is the first frame in which the ball crossed the threshold.
            if (
                abs(self.x - HALF_WIDTH) >= 344
                and abs(original_x - HALF_WIDTH) < 344
            ):
                # Now that we know the edge of the ball has crossed the threshold on the x-axis, we need to check to
                # see if the bat on the relevant side of the arena is at a suitable position on the y-axis for the
                # ball collide with it.

                if self.x < HALF_WIDTH:
                    new_dir_x: int = 1
                    bat: "Bat" = game.bats[0]
                else:
                    new_dir_x = -1
                    bat = game.bats[1]

                difference_y: float = self.y - bat.y

                if difference_y > -64 and difference_y < 64:
                    # Ball has collided with bat - calculate new direction vector

                    # To understand the maths used below, we first need to consider what would happen with this kind of
                    # collision in the real world. The ball is bouncing off a perfectly vertical surface. This makes for a
                    # pretty simple calculation. Let's take a ball which is travelling at 1 metre per second to the right,
                    # and 2 metres per second down. Imagine this is taking place in space, so gravity isn't a factor.
                    # After the ball hits the bat, it's still going to be moving at 2 m/s down, but it's now going to be
                    # moving 1 m/s to the left instead of right. So its speed on the y-axis hasn't changed, but its
                    # direction on the x-axis has been reversed. This is extremely easy to code - "self.dir.x = -self.dir.x".
                    # However, games don't have to perfectly reflect reality.
                    # In Pong, hitting the ball with the upper or lower parts of the bat would make it bounce diagonally
                    # upwards or downwards respectively. This gives the player a degree of control over where the ball
                    # goes. To make for a more interesting game, we want to use realistic physics as the starting point,
                    # but combine with this the ability to influence the direction of the ball. When the ball hits the
                    # bat, we're going to deflect the ball slightly upwards or downwards depending on where it hit the
                    # bat. This gives the player a bit of control over where the ball goes.

                    # Bounce the opposite way on the X axis
                    self.dir = Vector(-self.dir.x, self.dir.y)

                    # Deflect slightly up or down depending on where ball hit bat
                    self.dir = Vector(
                        self.dir.x, self.dir.y + difference_y / 128
                    )

                    # Limit the Y component of the vector so we don't get into a situation where the ball is bouncing
                    # up and down too rapidly
                    self.dir = Vector(
                        self.dir.x, min(max(float(self.dir.y), -1), 1)
                    )

                    # Ensure our direction vector is a unit vector, i.e. represents a distance of the equivalent of
                    # 1 pixel regardless of its angle. (A zero vector would
                    # raise, but dir.x is always +/-1 here.)
                    self.dir = self.dir.normalize()

                    # Create an impact effect
                    game.impacts.append(Impact(self.x - new_dir_x * 10, self.y))

                    # Increase speed with each hit
                    self.speed += 1

                    # Add an offset to the AI player's target Y position, so it won't aim to hit the ball exactly
                    # in the centre of the bat
                    game.ai_offset = random.randint(-10, 10)

                    # Bat glows for 10 frames
                    bat.timer = 10

                    # Play hit sounds, with more intense sound effects as the ball gets faster
                    game.play_sound("hit", 5)  # play every time in addition to:
                    if self.speed <= 10:
                        game.play_sound("hit_slow", 1)
                    elif self.speed <= 12:
                        game.play_sound("hit_medium", 1)
                    elif self.speed <= 16:
                        game.play_sound("hit_fast", 1)
                    else:
                        game.play_sound("hit_veryfast", 1)

            # The top and bottom of the arena are 220 pixels from the centre
            if abs(self.y - HALF_HEIGHT) > 220:
                # Invert vertical direction and apply new dy to y so that the ball is no longer overlapping with the
                # edge of the arena
                self.dir = Vector(self.dir.x, -self.dir.y)
                self.y += self.dir.y

                # Create impact effect
                game.impacts.append(Impact(self.x, self.y))

                # Sound effect
                game.play_sound("bounce", 5)
                game.play_sound("bounce_synth", 1)

    def out(self) -> bool:
        # Has ball gone off the left or right edge of the screen?
        return self.x < 0 or self.x > WIDTH


@dataclass(eq=False)
class Bat:
    player: int
    # move_func is a function we may or may not have been passed by the code which created this object. If this bat
    # is meant to be player controlled, move_func will be a function that when called, returns a number indicating
    # the direction and speed in which the bat should move, based on the keys the player is currently pressing.
    # If move_func is None, this indicates that this bat should instead be controlled by the AI method
    # (resolved in __post_init__, where self.ai exists).
    move_func_init: InitVar[Callable[[], float] | None] = None
    score: int = 0
    # Each bat has a timer which starts at zero and counts down by one every frame. When a player concedes a point,
    # their timer is set to 20, which causes the bat to display a different animation frame. It is also used to
    # decide when to create a new ball in the centre of the screen - see comments in Game.update for more on this.
    # Finally, it is used in Game.draw to determine when to display a visual effect over the top of the background
    timer: int = 0
    # x/y are the bat's CENTRE; set from `player` in __post_init__.
    x: float = 0.0
    y: float = 0.0
    image: str = "blank"

    def __post_init__(self, move_func_init: Callable[[], float] | None) -> None:
        self.x = 40.0 if self.player == 0 else 760.0
        self.y = float(HALF_HEIGHT)
        self.move_func = (
            move_func_init if move_func_init is not None else self.ai
        )

    def update(self) -> None:
        self.timer -= 1

        # Our movement function tells us how much to move on the Y axis
        y_movement: float = self.move_func()

        # Apply y_movement to y position, ensuring bat does not go through the side walls
        self.y = min(400, max(80, self.y + y_movement))

        # Choose the appropriate sprite. There are 3 sprites per player - e.g. bat00 is the left-hand player's
        # standard bat sprite, bat01 is the sprite to use when the ball has just bounced off the bat, and bat02
        # is the sprite to use when the bat has just missed the ball and the ball has gone out of bounds.
        # bat10, 11 and 12 are the equivalents for the right-hand player

        frame: int = 0
        if self.timer > 0:
            if game.ball.out():
                frame = 2
            else:
                frame = 1

        self.image = "bat" + str(self.player) + str(frame)

    def ai(self) -> float:
        # Returns a number indicating how the computer player will move - e.g. 4 means it will move 4 pixels down
        # the screen.

        # To decide where we want to go, we first check to see how far we are from the ball.
        x_distance: float = abs(game.ball.x - self.x)

        # If the ball is far away, we move towards the centre of the screen (HALF_HEIGHT), on the basis that we don't
        # yet know whether the ball will be in the top or bottom half of the screen when it reaches our position on
        # the X axis. By waiting at a central position, we're as ready as it's possible to be for all eventualities.
        target_y_1: int = HALF_HEIGHT

        # If the ball is close, we want to move towards its position on the Y axis. We also apply a small offset which
        # is randomly generated each time the ball bounces. This is to make the computer player slightly less robotic
        # - a human player wouldn't be able to hit the ball right in the centre of the bat each time.
        target_y_2: float = game.ball.y + game.ai_offset

        # The final step is to work out the actual Y position we want to move towards. We use what's called a weighted
        # average - taking the average of the two target Y positions we've previously calculated, but shifting the
        # balance towards one or the other depending on how far away the ball is. If the ball is more than 400 pixels
        # (half the screen width) away on the X axis, our target will be half the screen height (target_y_1). If the
        # ball is at the same position as us on the X axis, our target will be target_y_2. If it's 200 pixels away,
        # we'll aim for halfway between target_y_1 and target_y_2. This reflects the idea that as the ball gets closer,
        # we have a better idea of where it's going to end up.
        weight1: float = min(1, x_distance / HALF_WIDTH)
        weight2: float = 1 - weight1

        target_y: float = (weight1 * target_y_1) + (weight2 * target_y_2)

        # Subtract target_y from our current Y position, then make sure we can't move any further than MAX_AI_SPEED
        # each frame
        return min(MAX_AI_SPEED, max(-MAX_AI_SPEED, target_y - self.y))


# Not a dataclass: every attribute is derived from the `controls` parameter,
# so a generated __init__ would add nothing (all fields would be init=False).
class Game:
    def __init__(
        self, controls: Sequence[Callable[[], int] | None] = (None, None)
    ) -> None:
        # Create a list of two bats, giving each a player number and a function to use to receive
        # control inputs (or the value None if this is intended to be an AI player)
        self.bats: list[Bat] = [Bat(0, controls[0]), Bat(1, controls[1])]

        # Create a ball object
        self.ball: Ball = Ball(Vector(-1, 0))

        # Create an empty list which will later store the details of currently playing impact
        # animations - these are displayed for a short time every time the ball bounces
        self.impacts: list[Impact] = []

        # Add an offset to the AI player's target Y position, so it won't aim to hit the ball exactly
        # in the centre of the bat
        self.ai_offset: int = 0

    def update(self) -> None:
        # Update all active objects
        for obj in [*self.bats, self.ball, *self.impacts]:
            obj.update()

        # Remove any expired impact effects from the list. We go through the list backwards, starting from the last
        # element, and delete any elements those time attribute has reached 10. We go backwards through the list
        # instead of forwards to avoid a number of issues which occur in that scenario. In the next chapter we will
        # look at an alternative technique for removing items from a list, using list comprehensions.
        for i in range(len(self.impacts) - 1, -1, -1):
            if self.impacts[i].time >= 10:
                del self.impacts[i]

        # Has ball gone off the left or right edge of the screen?
        if self.ball.out():
            # Work out which player gained a point, based on whether the ball
            # was on the left or right-hand side of the screen
            scoring_player: int = 1 if self.ball.x < WIDTH // 2 else 0
            losing_player: int = 1 - scoring_player

            # We use the timer of the player who has just conceded a point to decide when to create a new ball in the
            # centre of the level. This timer starts at zero at the beginning of the game and counts down by one every
            # frame. Therefore, on the frame where the ball first goes off the screen, the timer will be less than zero.
            # We set it to 20, which means that this player's bat will display a different animation frame for 20
            # frames, and a new ball will be created after 20 frames
            if self.bats[losing_player].timer < 0:
                self.bats[scoring_player].score += 1

                game.play_sound("score_goal", 1)

                self.bats[losing_player].timer = 20

            elif self.bats[losing_player].timer == 0:
                # After 20 frames, create a new ball, heading in the direction of the player who just missed the ball
                direction: int = -1 if losing_player == 0 else 1
                self.ball = Ball(Vector(direction, 0))

    def draw(self) -> None:
        # Draw background
        blit("table", 0, 0)

        # Draw 'just scored' effects, if required
        for p in (0, 1):
            if self.bats[p].timer > 0 and game.ball.out():
                blit("effect" + str(p), 0, 0)

        # Draw bats, ball and impact effects - in that order. Square brackets are needed around the ball because
        # it's just an object, whereas the other two are lists - and you can't directly join an object onto a
        # list without first putting it in a list
        for obj in [*self.bats, self.ball, *self.impacts]:
            draw_sprite(obj.image, obj.x, obj.y)

        # Display scores - outer loop goes through each player
        for p in (0, 1):
            # Convert score into a string of 2 digits (e.g. "05") so we can later get the individual digits
            score: str = "{0:02d}".format(self.bats[p].score)
            # Inner loop goes through each digit
            for i in (0, 1):
                # Digit sprites are numbered 00 to 29, where the first digit is the colour (0 = grey,
                # 1 = blue, 2 = green) and the second digit is the digit itself
                # Colour is usually grey but turns red or green (depending on player number) when a
                # point has just been scored
                colour: str = "0"
                other_p: int = 1 - p
                if self.bats[other_p].timer > 0 and game.ball.out():
                    colour = "2" if p == 0 else "1"
                image: str = "digit" + colour + str(score[i])
                blit(image, 255 + (160 * p) + (i * 55), 46)

    def play_sound(
        self, name: str, count: int = 1, menu_sound: bool = False
    ) -> None:
        # Some sounds have multiple varieties. If count > 1, we'll randomly choose one from those
        # We don't play any in-game sound effects if player 0 is an AI player - as this means we're on the menu
        # Updated Jan 2022 - some Pygame installations have issues playing ogg sound files. play_sound can skip sound
        # errors without stopping the game, but it previously couldn't be used for menu-only sounds
        if self.bats[0].move_func != self.bats[0].ai or menu_sound:
            # Pygame Zero allows you to write things like 'sounds.explosion.play()'
            # This automatically loads and plays a file named 'explosion.wav' (or .ogg) from the sounds folder (if
            # such a file exists)
            # But what if you have files named 'explosion0.ogg' to 'explosion5.ogg' and want to randomly choose
            # one of them to play? You can generate a string such as 'explosion3', but to use such a string
            # to access an attribute of Pygame Zero's sounds object, we must use Python's built-in function getattr
            try:
                getattr(sounds, name + str(random.randint(0, count - 1))).play()
            except Exception:
                pass


def p1_controls() -> int:
    move: int = 0
    if keyboard.z or keyboard.down:
        move = PLAYER_SPEED
    elif keyboard.a or keyboard.up:
        move = -PLAYER_SPEED
    return move


def p2_controls() -> int:
    move: int = 0
    if keyboard.m:
        move = PLAYER_SPEED
    elif keyboard.k:
        move = -PLAYER_SPEED
    return move


class State(Enum):
    MENU = 1
    PLAY = 2
    GAME_OVER = 3


num_players: int = 1

# Is space currently being held down?
space_down: bool = False


# Pygame Zero calls the update and draw functions each frame


def update() -> None:
    global state, game, num_players, space_down

    # Work out whether the space key has just been pressed - i.e. in the previous frame it wasn't down,
    # and in this frame it is.
    space_pressed: bool = False
    if keyboard.space and not space_down:
        space_pressed = True
    space_down = keyboard.space

    match state:
        case State.MENU:
            if space_pressed:
                # Switch to play state, and create a new Game object, passing it the controls function for
                # player 1, and if we're in 2 player mode, the controls function for player 2 (otherwise the
                # 'None' value indicating this player should be computer-controlled)
                state = State.PLAY
                controls: list[Callable[[], int] | None] = [p1_controls]
                controls.append(p2_controls if num_players == 2 else None)
                game = Game(controls)
            else:
                # Detect up/down keys
                if num_players == 2 and keyboard.up:
                    game.play_sound("up", menu_sound=True)
                    num_players = 1
                elif num_players == 1 and keyboard.down:
                    game.play_sound("down", menu_sound=True)
                    num_players = 2

                # Update the 'attract mode' game in the background (two AIs playing each other)
                game.update()

        case State.PLAY:
            # Has anyone won?
            if max(game.bats[0].score, game.bats[1].score) > 9:
                state = State.GAME_OVER
            else:
                game.update()

        case State.GAME_OVER:
            if space_pressed:
                # Reset to menu state
                state = State.MENU
                num_players = 1

                # Create a new Game object, without any players
                game = Game()


def draw() -> None:
    game.draw()

    match state:
        case State.MENU:
            menu_image: str = "menu" + str(num_players - 1)
            blit(menu_image, 0, 0)

        case State.GAME_OVER:
            blit("over", 0, 0)


# The mixer allows us to play sounds and music
try:
    mixer.quit()
    mixer.init(44100, -16, 2, 1024)

    music.play("theme")
    music.set_volume(0.3)
except Exception:
    # If an error occurs (e.g. no sound device), just ignore it
    pass

# Set the initial game state
state = State.MENU

# Create a new Game object, without any players
game: Game = Game()

# --- boing owns its game loop ------------------------------------------------
# Was pgzero_gl.runner.main(): a framework that owned the loop and called back
# into this module's update()/draw(). Now boing runs the loop itself and calls
# *down* into the renderer -- the course's library-not-framework style, the same
# shape as the modelviewprojection demos.
if __name__ == "__main__":
    Context.asset_root = os.path.dirname(os.path.abspath(__file__))

    if not glfw.init():
        raise RuntimeError("glfw.init() failed")
    Context.glfw_ready = True
    # OpenGL 2.1 compatibility context: 2.1 predates the core/compat profile
    # split, so request version 2.1 with the default (ANY) profile and no
    # forward-compat. The fixed-function pipeline this game draws with (glOrtho
    # + glBegin) is not available in a 3.3 core context -- that is the whole
    # point of this GL 1.x variant. See boing.py for the 3.3-core original.
    glfw.window_hint(glfw.CONTEXT_VERSION_MAJOR, 2)
    glfw.window_hint(glfw.CONTEXT_VERSION_MINOR, 1)
    window = glfw.create_window(WIDTH, HEIGHT, TITLE, None, None)
    if not window:
        glfw.terminate()
        raise RuntimeError("glfw.create_window() failed")
    glfw.make_context_current(window)
    glfw.swap_interval(1)
    # No VAO: the fixed-function pipeline needs none (VAOs are a 3.0+ construct).
    Context.window = window
    Context.renderer = Renderer1x(WIDTH, HEIGHT)

    def _key_cb(
        win: Any, key: int, scancode: int, action: int, mods: int
    ) -> None:
        if action == glfw.PRESS:
            keyboard._press(key)
            if key == glfw.KEY_ESCAPE:  # Esc always quits (no title-bar needed)
                glfw.set_window_should_close(win, True)
        elif action == glfw.RELEASE:
            keyboard._release(key)

    glfw.set_key_callback(window, _key_cb)

    # Ctrl-C / SIGTERM (e.g. `podman stop`) ask the window to close between
    # frames; handlers are restored in the finally. Main-thread only.
    def _request_quit(_signum: int, _frame: Any) -> None:
        glfw.set_window_should_close(window, True)

    _prev_handlers: list[tuple[int, Any]] = []
    for _sig in (signal.SIGINT, signal.SIGTERM):
        try:
            _prev_handlers.append((_sig, signal.signal(_sig, _request_quit)))
        except (ValueError, OSError):
            pass

    # Fixed 60 Hz timestep -- boing's update() takes no dt.
    _max_frames = int(os.environ.get("PGZERO_MAX_FRAMES", "0") or 0)
    _dt = 1.0 / 60.0
    _next_t = time.perf_counter()
    _frame_count = 0
    try:
        while not glfw.window_should_close(window):
            glfw.poll_events()
            update()
            fb_w, fb_h = glfw.get_framebuffer_size(window)
            Context.renderer.begin_frame(fb_width=fb_w, fb_height=fb_h)
            draw()
            glfw.swap_buffers(window)
            _frame_count += 1
            if _max_frames and _frame_count >= _max_frames:
                break
            _next_t += _dt
            _sleep = _next_t - time.perf_counter()
            if _sleep > 0:
                time.sleep(_sleep)
            else:
                _next_t = time.perf_counter()
    finally:
        for _sig, _prev in _prev_handlers:
            try:
                signal.signal(_sig, _prev)
            except (ValueError, OSError):
                pass
        # Stop the audio device's native callback thread before exit, else a
        # music-playing game hangs the process after the window closes.
        audio.shutdown()
        glfw.terminate()
