# Copyright (c) 2026 William Emerison Six
# SPDX-License-Identifier: LGPL-2.1-only
# Generated by Claude (Anthropic); a clean-room reimplementation of the pygame /
# PyGame Zero APIs, under the same license as pygame (GNU LGPL v2.1).
# Full license text: ports/codetheclassics/pgzero_gl/LICENSE.
# License source: https://raw.githubusercontent.com/pygame/pygame/main/docs/LGPL.txt

# pgzero_gl -- headless render smoke test.
#
# Part of the ModelViewProjection "Code the Classics" port.  Originals (c)
# Raspberry Pi Press and authors.
#   Repo: https://github.com/raspberrypipress/Code-the-Classics-Vol1
#   Book: https://magazine.raspberrypi.com/books/code-the-classics-vol-I-2ed
#
# Renders ONE frame of a ported game to an offscreen EGL pbuffer (Mesa
# llvmpipe -- no display/GPU needed) and writes a PNG, so a port's rendering can
# be pixel-checked in CI / the build container, not just by eye on a real
# window.  This is how the integer-tint black-screen bug was found + fixed.
#
# Usage:
#   python _smoketest.py vol1/boing/boing.py            # -> /tmp/boing.png
#   python _smoketest.py vol2/eggzy/eggzy.py out.png
#
# The game's update()/draw() globals are driven for a few frames first.  Games
# that need a specific state (eggzy needs a Game in PLAY) get a small hook below.

import ctypes
import importlib.util
import os
import string
import sys
import types

import numpy as np
from PIL import Image as PILImage

os.environ.setdefault("EGL_PLATFORM", "surfaceless")
from OpenGL import EGL, GL  # noqa: E402


def make_context(w, h, legacy=False):
    dpy = EGL.eglGetDisplay(EGL.EGL_DEFAULT_DISPLAY)
    maj, mn = ctypes.c_long(), ctypes.c_long()
    if not EGL.eglInitialize(dpy, maj, mn):
        raise RuntimeError("eglInitialize failed (no EGL device?)")
    EGL.eglBindAPI(EGL.EGL_OPENGL_API)
    ca = (EGL.EGLint * 13)(
        EGL.EGL_SURFACE_TYPE,
        EGL.EGL_PBUFFER_BIT,
        EGL.EGL_RENDERABLE_TYPE,
        EGL.EGL_OPENGL_BIT,
        EGL.EGL_RED_SIZE,
        8,
        EGL.EGL_GREEN_SIZE,
        8,
        EGL.EGL_BLUE_SIZE,
        8,
        EGL.EGL_ALPHA_SIZE,
        8,
        EGL.EGL_NONE,
    )
    cfg, n = EGL.EGLConfig(), EGL.EGLint()
    EGL.eglChooseConfig(dpy, ca, ctypes.byref(cfg), 1, ctypes.byref(n))
    if legacy:
        # Compatibility 2.1 context -> fixed-function GL 1.x available.
        cxa = (EGL.EGLint * 5)(
            EGL.EGL_CONTEXT_MAJOR_VERSION,
            2,
            EGL.EGL_CONTEXT_MINOR_VERSION,
            1,
            EGL.EGL_NONE,
        )
    else:
        cxa = (EGL.EGLint * 7)(
            EGL.EGL_CONTEXT_MAJOR_VERSION,
            3,
            EGL.EGL_CONTEXT_MINOR_VERSION,
            3,
            EGL.EGL_CONTEXT_OPENGL_PROFILE_MASK,
            EGL.EGL_CONTEXT_OPENGL_CORE_PROFILE_BIT,
            EGL.EGL_NONE,
        )
    ctx = EGL.eglCreateContext(dpy, cfg, EGL.EGL_NO_CONTEXT, cxa)
    pa = (EGL.EGLint * 5)(EGL.EGL_WIDTH, w, EGL.EGL_HEIGHT, h, EGL.EGL_NONE)
    surf = EGL.eglCreatePbufferSurface(dpy, cfg, pa)
    EGL.eglMakeCurrent(dpy, surf, surf, ctx)
    if not legacy:
        GL.glBindVertexArray(GL.glGenVertexArrays(1))


def _stub_glfw():
    glfw = types.ModuleType("glfw")
    for ch in string.ascii_uppercase:
        setattr(glfw, "KEY_" + ch, ord(ch))
    for d in string.digits:
        setattr(glfw, "KEY_" + d, ord(d))
    for nm, v in dict(
        KEY_SPACE=32,
        KEY_UP=200,
        KEY_DOWN=201,
        KEY_LEFT=202,
        KEY_RIGHT=203,
        KEY_ENTER=257,
        KEY_ESCAPE=256,
        KEY_TAB=258,
        KEY_BACKSPACE=259,
        KEY_LEFT_SHIFT=340,
        KEY_RIGHT_SHIFT=344,
        KEY_LEFT_CONTROL=341,
        KEY_RIGHT_CONTROL=345,
        KEY_LEFT_ALT=342,
        KEY_RIGHT_ALT=346,
        PRESS=1,
        RELEASE=0,
    ).items():
        setattr(glfw, nm, v)
    sys.modules["glfw"] = glfw


# Per-game state hooks: get the game into a drawable state before the frame.
def _setup(mod, name):
    if name == "eggzy":
        mod.game = mod.Game(player=mod.Player(mod.KeyboardControls()))
        mod.state = mod.State.PLAY
    for _ in range(5):
        try:
            mod.update()
        except Exception:
            break


def main():
    args = [a for a in sys.argv[1:] if not a.startswith("-")]
    gl1 = ("--gl1" in sys.argv) or os.environ.get("PGZERO_GL", "").lower() in (
        "1",
        "gl1",
        "legacy",
        "1.4",
        "1.5",
        "fixed",
    )
    path = os.path.abspath(args[0])
    name = os.path.splitext(os.path.basename(path))[0]
    out = (
        args[1]
        if len(args) > 1
        else "/tmp/%s%s.png" % (name, "_gl1" if gl1 else "")
    )

    _stub_glfw()
    sys.modules.setdefault("just_playback", types.ModuleType("just_playback"))
    here = os.path.dirname(os.path.abspath(__file__))
    sys.path.insert(0, here)

    gamedir = os.path.dirname(os.path.abspath(path))
    sys.path.insert(0, gamedir)
    os.chdir(
        gamedir
    )  # games open data files (e.g. attacks.json) by relative path

    import pgzero_gl
    from pgzero_gl import context

    context.glfw_ready = True  # let joystick query (stubbed) but stay safe

    # Read WIDTH/HEIGHT from the game source without running it yet.
    src = open(path, encoding="utf-8").read()
    g = {}
    exec(compile(src, path, "exec"), g) if False else None
    w = h = None
    for line in src.splitlines():
        s = line.strip()
        if s.startswith("WIDTH") and "=" in s and w is None:
            w = int(s.split("=")[1].split("#")[0])
        if s.startswith("HEIGHT") and "=" in s and h is None:
            h = int(s.split("=")[1].split("#")[0])
    w, h = w or 800, h or 600

    make_context(w, h, legacy=gl1)
    context.asset_root = gamedir
    if gl1:
        from pgzero_gl.renderer_gl1 import Renderer1x

        context.renderer = Renderer1x(w, h)
    else:
        from pgzero_gl import renderer

        context.renderer = renderer.Renderer(w, h)
    pgzero_gl.pgzrun.go = lambda gl=None: None

    spec = importlib.util.spec_from_file_location("game_under_test", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["game_under_test"] = mod
    spec.loader.exec_module(mod)

    _setup(mod, name)
    context.renderer.begin_frame(w, h)
    mod.draw()
    GL.glFinish()
    px = np.frombuffer(
        GL.glReadPixels(0, 0, w, h, GL.GL_RGBA, GL.GL_UNSIGNED_BYTE), np.uint8
    ).reshape(h, w, 4)
    px = np.flipud(px)  # GL is bottom-up; PNG is top-down
    PILImage.fromarray(px, "RGBA").save(out)
    nb = int((px[..., :3].sum(2) > 10).sum())
    print(
        "%s: %dx%d, %d%% non-black, %d distinct colours -> %s"
        % (
            name,
            w,
            h,
            100 * nb // (w * h),
            len(np.unique(px[..., :3].reshape(-1, 3), axis=0)),
            out,
        )
    )
    if nb < w * h * 0.2:
        print("WARNING: frame is mostly black -- likely a render bug.")
        sys.exit(1)


if __name__ == "__main__":
    main()
